---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fredy-data
  namespace: fredy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fredy-config
  namespace: fredy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 1Gi
