apiVersion: v1
kind: Secret
metadata:
    name: b2-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:pQsviVLXaPTbjx518bu9TI83eE9rgNJeVJdXUXExDjP3nKRoeIdP8EM3OBOSSAWfAywFT74T4SifEZttv2gtsz4Ppc2GKpNsXVCwrzI3Gd3FHyIUwzVqszYLvVTve56WOiqvIG5G9dUTkT6KwtvzWR0=,iv:z462rGiGkCSa8awyPct1kFE1GlAVWXPv3KiZ28Ax6Pc=,tag:xlmyNsmFr2Z0J7LZoH8smA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bkhGTEtZUGxpWXU1YVRl
            emdOb2k3ZUdGaUVLRXg0c0xsVEw4ZGZsMWtzCjErbkU3VkJnTm9sdHgrMXlFMzJU
            YkNKZXVSVFJtanRGMVd4RDZqNjhMVkkKLS0tIDhQd0ovZW1LY2o5MkY3UnlNSlRX
            V0c2MXpIKzVVN1dyam0wQ2R5ZERXdXMKDShFwrUm7UE3em6//QndbU2g+XWMNmFR
            Ja+jT2ZKr5MCISLQ1g4csXuGpShWnbHQQfgefhNmooCZaHERjEkIVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:38:29Z"
    mac: ENC[AES256_GCM,data:2mAcVhN1SGI9JkuJjMThWdTzmiSWr6+E14R5kBmN5DvgIf7pAVydt35G7hpBHFi9pfkqa17nOGFhql6jyhc2WZ9LESB2rUNKAx60ce2VMYE5XTzLRgixO9jjsdxYX56dOfumhkUF0pvr/K24sROX2tYItByJZ77xcMWEtAeTcJw=,iv:bqlp1xuJmC2o+55H5KY/ntdkJgbhesr8ldfaBwwZXyc=,tag:Gps2q4ZekoIIeCG/4LXAyA==,type:str]
    version: 3.13.3
