apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cnpg-b2-credentials
    namespace: wardrowbe
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:eauXGGqd+HE1W3br4eCKDgB3imubFX36Jg==,iv:4YQGqDCA2OR0dVDIpziiUaYONj+12GdYoyyt7N8ORwc=,tag:/iOUQ0F4VdkwXPr4x+eMAw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:JO5fY6ZvESD9A5KtwA+SKXuEmsK7eJ90CbO3euhiTg==,iv:uBA/jW5VA747TIuQHHONlAMNiWWL+WB64qOPj81YYsw=,tag:gXY7LfSfq+oaCfhG9VkySA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxalVIeHhhdFRpUGF2U2tT
            aDdNTnhIcWtFcWo3Wk5vNE1CaTJ5dmpER1g0CkNHcUJ3eUlkMXgrNll3cmhZbmZC
            VXZqWUd1YU1pVVg4enE0RkdlYXRjOUEKLS0tIHFKaDFWRDFyNXU3OXBxVGp5UzJJ
            ZnlqQjJia1lxaFNLUEFYRU5BQkFselUKNWUEhyxqCiVnX+6FcsSqPQfV+gYkWJaW
            8maFoF+ch8UjUviouhIOwP+PwKgY5Ds4VUHNGO4f+FTuaUFoa2E41A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:38:29Z"
    mac: ENC[AES256_GCM,data:rgPij84YylmJvROZqJ4AqQrMqGUbSy218dyeNS9AJS+ctXFUqNs9TQ6wRsBGSzMB8VA6imBw9rhM0LAcwqWAwjgT7sZIRAPi12N6mwFvFACZjN/imliEBzHOCSRlHXeYyL85Ow+KLROnA0g2uhBMgPGawgGCrevNfz/phNEYb6A=,iv:PCLzREfSwcnLCQ6vgnuWkAK4LQ+9Hun4qhpdfLYjORo=,tag:HJnu/14pGubxUVbz0TkuGQ==,type:str]
    version: 3.13.3
