apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wardrowbe
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - cnpg-b2-credentials-secret.yaml
  - redis.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
components:
  - ../../infrastructure-config/networkpolicies/default-deny-ingress
  - ../../infrastructure-config/networkpolicies/allow-intra-namespace
  - ../../infrastructure-config/networkpolicies/allow-from-traefik
  - ../../infrastructure-config/networkpolicies/allow-from-monitoring
  - ../../infrastructure-config/networkpolicies/allow-from-homepage
