apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wardrowbe-uploads
  namespace: wardrowbe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hdd1
  resources:
    requests:
      storage: 20Gi
