apiVersion: v1
kind: Secret
metadata:
    name: wardrowbe-credentials
    namespace: wardrowbe
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:y8Q6WMlm6n2T,iv:hRhlo6KF9jAzoE+NsAprrX5kI1DDgYddP7eEe3Rfr0c=,tag:vkq5Wot6Ls78+gFu5TBk+g==,type:str]
    password: ENC[AES256_GCM,data:j0ulQHxkLFRoeuYRpkMEiA0dBBgODYVbd+uMfWWUgX5CcEpeBvhbC3uGJosAY4fQSLMi9Ktphu2r0mv5wJYW9Q==,iv:b1BqYIAkF02ksW/Mct5iymgP1NqYZojedtJNezeFytQ=,tag:XukG3EUShh6XBldsWXsOOw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:mWunzT3IMXECnB/oF3a0G0zeBTUL0jQqB7CqNiAW8alWVQDIF1W/VRKnRRwq2gA4HVBjJN3qenVuDNdhAZBd5HVVN+LZYH3jFnupseohvoeO549oedVUsWvA7vJcVx+Z3L6ro2AhQj+rwsPUp+vjkWSmfEhgQMuJB+UuUO3GzdVe65GgbSA=,iv:YyJVt8aOAqHC1V0DEqs5HiQXN4MyCLqo/syFRMNduSw=,tag:wS7yvLHqSkUCryYqXeEYHA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:fUVTtOg/S46oWOY15HFvrZlSJRSDQ7YYa4B5bzKZ6rxcnJz1XaNRSqnCpyNxoViRx93YxmwHGDZRp471ZvsHkA==,iv:Ju9LpYwBYNY8cYGtOdHZPqPMVFzIJthgpD5oonhV/ws=,tag:BmnfGZxB+4V5TP7jN2KLCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeXNESDZQMVBWeWQvY1R0
            QVZmU1o4K0ViNVl3ZENDRkMwczJETEpSNzFRCmNmd2l3RkxVZ2JTZWdsd0VjaFhp
            a2FqazI1NHk0cXo1eGl0cEJWbFFvdTQKLS0tIFdndTFmQjEySWhYbWFQbElzWXNT
            eGZpQVd4NnBITzhKTUJXaXdRTEEwbXcKXxke4zJuur70M5gKS+djdFFlmJND1ZoL
            fqyerhRisOmPAuxW24xF48Ok2l0mKT7AbMRPI8Hg4TYOfuTgbMpYVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T16:16:04Z"
    mac: ENC[AES256_GCM,data:ONwnazD7bS/BLMrJUQbM3bqj7blRlCnm6f0G6frhNfirzKf+e/wz4mZ8N4iEzH110+HMXKzFX84Qv6Ab/9P1hQ4944xQupMmISCLa+p8AGZzHaiWQ40KEf5Zt2XlLL8Bivy82Rdm41fcljUB+GSmFDnZXst9ZJBGTsBVZTRaaJ0=,iv:MgrfVio55adtl5yBys2asr2fnQkNe1qjogMiWKv/GTc=,tag:HIXRG9KipIGSDGiLztg50g==,type:str]
    version: 3.13.2
