apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cnpg-b2-credentials
    namespace: n8n
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:9PeDhfCZZv3yZfxPH6eB9Gpy+ZidZPuQZw==,iv:e6aFjI4oQRePgFqEOrA2h4wT+zxmS8yzP2GnsX5ywsg=,tag:8GK4ncxGopZVTueGYw+DbA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:gKQjffGE761JB5y7yUO2gT4M0WUKQaVZeXtf18s3rw==,iv:PyARzamKw2ZORT/6W4DZsouwIIUkpmSG1N3qjAhWjL8=,tag:lZevltoVJHYQtlilUMP5Ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUFczMWNaaTNzTm0vd3pu
            aXBVUlZjV216eFZvQ0RYTmpsSFFJcy9KeVVNCkVacEhKSkVVRC9CZE5IZ0hiLzBj
            WTlQTHprdGxpTW5zVVhUemJlY0VheWsKLS0tIE1peGduRXdwTkhaaG4vSG80Qnpx
            QlF2Y2wzMCszNzdGWldBRm5Rd1hieE0KdkQIVnUAcqZ1ofmMuNfUO/32KMWPxZoP
            nhwERwx79Z52cQo1+G6BhQAn3ak/WEuUwPaCR0fuO3OicaRhFUOcTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:38:29Z"
    mac: ENC[AES256_GCM,data:twACnTvPjb8PWMW0PIujwjhsQ1/HlDHpF/diSh7xwFK3C3G9BeyH/V6dVl+jsTqO+x5Cbxm+bahcrUV8Zh/mJvi2zcsA/TqUzhOk9bVSm+puEWrkZUUCj1bASgqp3jfv1h45GzFxP1WdnarpNuZlhjqzUr6Zv7gk+GFbny5Nd6E=,iv:9756H4XAebZESi/3YahwLuSAGxP051d6XvMqH4qJSFM=,tag:JkiJAh++dr4pxieupULEjA==,type:str]
    version: 3.13.3
