apiVersion: v1
kind: Secret
metadata:
    name: n8n-credentials
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:09Pf,iv:buD2qmF2+WsBXMNsk0aRq2l6AIKzVJ2Y1zmiRINAOGU=,tag:AOGm4Z9XuRawAt3C2KaBjQ==,type:str]
    password: ENC[AES256_GCM,data:ugBa4SY62ECrLAEYO/o8ZQjWATTW8T8j,iv:W9PcA95S8gP2E8lRUqvy676cwZYrC+vigq3J86Etako=,tag:fL3Xev8S6ZrRn90ZJDrTkg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vowrpfDaNs7aa45zTRGy9+mhucTRxcnt,iv:uIpPYZNX5GixssmPzYyclgCjVNNpWLJZAK2enGzkJBE=,tag:iBTufl0smEzgjoJefytGUg==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:HQuGRFUrw7tepVH+5TZntQnbK4TBSzHCyWxGZQ1O6WLSFN0HgIzGj3kmHr8=,iv:S30USVIggrW7Mp+dR1a16Lt+rEVG8nPHIXwXXDiBlMk=,tag:4qtu9Gdp4mkm70gvEYblWg==,type:str]
    N8N_JWT_HEADER_AUTH_TOKEN: ENC[AES256_GCM,data:rG6sjDXZy1a8yLbamrwzKvOjauDkk1igRmPurMpmtXAjSXYRz0uRvTfHA7w=,iv:c1NDwo8A14qotT6HkE90MlTwrkfMh+iyrBOy+tabjOY=,tag:sQhLuC5hu6Mp1McRjJ2hMQ==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMUliQ3B5ZFhxdDQvdlgy
            UnNPZHBreENXTi93aUcrRFdkNTlpS0liYm5nCittWHlBd3JScmQrQUhWTUFkYW51
            QndoMWN1eVp3Rkt3QkhvU3NXRy85OWMKLS0tIGNRVHd3N1l1alBHQ0s0b202TXA2
            K0hyWW4yaWFpSDRCbHdLa3RaOEk0V0EKbY6skWxl2xo4prUskxRi+v2s2UOiGhKC
            Sejon/Ndm6p91BZ/OvdICN/fR9JqrBH3f3wXhYAo33whNOrDRG2/1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T22:32:54Z"
    mac: ENC[AES256_GCM,data:0aDSXkOoAzmA9797uqnZYlse2EL28t+hODXn2TzxX5Y9BNumCYDClEXmkbHcuZzNJn/HrWThb52VXelC8lEwZwIYlqup8DHiAjHqZY7HGSwq7NGsht61QYxQb+tJtNyUBQRjUJSKS3RYsCozsTw3N/TOy34O763LzbEkQ2ICW3w=,iv:l1/7OkTHpBYDFjHpSUOqIgOppeoht4socFNpsBVRgEc=,tag:C9ui7ygt4AN80CoJ092MCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
