apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: crowdsec-secrets
    namespace: crowdsec
stringData:
    csLapiSecret: ENC[AES256_GCM,data:NNW4g+t8qIj+qhhRfYwOmvIbPEowv+BM3ESE2AvQNi7/wPhGGgnrc8kmDTttOYzSSIhRtAlc+weqS9B40oDF9S3p+I60h+U7nAdtQXptoWcTLBzeUNoIceMfS0JdHUoI,iv:chS8yzlsSvTk+4yIEVGT+KKw54dx9xe813RPmtwaqfo=,tag:EXNEoMcGPa5pB26jH8+63g==,type:str]
    registrationToken: ENC[AES256_GCM,data:nyXvApU3KkS+ckmwdp8vhNa+qYedwqdafUvAwrFlb+1Auy9vxphhjPo6H5uEhyaX7Hlgvk+4qx+2/A9F8E18jA==,iv:XKCiF2rJeRwLxdFIAM0u+aN8Jt9QDy+tBirRy6m/PHk=,tag:ZovZo//qf15bD5e1bHcMLg==,type:str]
    bouncerKey: ENC[AES256_GCM,data:bSN+PCSA9EVv7H6vkpSFi22SKscD+68JLFSy5W6SpoFEhtIkAYSqSVfdUvhcQ+Fm8hIgMS59I6aA7VxzRfdp8g==,iv:fsODcs0DVajCNbunBh4mE/j/uDW8GeDO5R1CA5LI1Dk=,tag:vW1HHAh/DtQCugJaSUe1mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMlNVQW1MSHpWcTlaYVky
            ZUVndTA5RmhEM0FLQXJMZXQ0TXRZU0R0K0F3CkdjampDOUpMZXJXVVZoc0o1ZUE0
            bW1DK21KcGJCRHJCS3lwdTNNRnNXUjQKLS0tIERQSks4d1hJc1I4NHpPczhGcGxq
            M1dKYlJwUTdtUVpXK0h1ckNxNmptb0UK8T8AAbJWirWpO+/gBThHivD2EXx30FPI
            FPg0XVJ0vtNhYY3oCE3oopsx2ZYndpZBXFL+rV45bOHulDumERAatw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T21:53:26Z"
    mac: ENC[AES256_GCM,data:OiVE4DlKUC9u5i9HHDRarqzanOB1Fl2KJgr5AuRQ+IqoFchMCDynsL2gEsYZmbUcuQDJmSq6mq6iFGcMtC6FJQ+5hv8BjKbyK+fxiatypeHwB/BUyFqiw0JqWyJhpiJjtbWxENXPFOWetiQDIrGPBaW++QJwrAl6noQxvoBv/bI=,iv:ZH63NXLp64kkt5M2/gHhywOvOKmewgqFKiYbL9nj6Sw=,tag:TPNHJrOvt5nLClA7gxnuXQ==,type:str]
    version: 3.13.3
