creation_rules:
  - path_regex: kubernetes/.*\.ya?ml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      # TODO: Add age public key after generation
      # age1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq

  - path_regex: nix/secrets/.*\.ya?ml$
    age: >-
      # TODO: Add age public key after generation
      # age1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
