---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sure
  namespace: sure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`finance.pxldi.de`)
      kind: Rule
      services:
        - name: sure-web
          port: 3000
      middlewares:
        - name: authentik-forward-auth
          namespace: traefik
