---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-app-storage
  namespace: sure
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-ssd
  resources:
    requests:
      storage: 5Gi
