apiVersion: v1
kind: Secret
metadata:
    name: sure-secrets
    namespace: sure
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:B02GdjJ90WYCeH2x0evYmbroSK9jPbBprFeGzlcoicNul/d+ubsdLsX9enYLbZ64Q3nr/+gzC77h1/aPTVydspnFPv3dCKt9HBMbQVjif+CLNBun9gBx7/LZwWQ7eeWIeGGjJzFMWvVoQS+4jcnRSTnBajV0+5jUwk2BHgiyuQU=,iv:hoj2C+JS/Of7B8lOB4qWuAZK6zqrIJCe+XnwFUFjALE=,tag:7TSMnLE9WDHV4a/ZE3XiCg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Uf4znQqvynhgKKkh84PUpJOfxZqFKshUmVYm6jWpxHY=,iv:9aqmqk8fer+RleVzeXX7oU6aoC4oDYymLJAX8euX2bs=,tag:Jsvjp1TAF3yRu8bWbt+wvQ==,type:str]
    OPENAI_ACCESS_TOKEN: ""
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS1JpblR4WXNONndRSXM3
            Mk92dHBuUnJSY3ZueStoRmJ2V09RMTZSd1NvCnN6d1ErakVaRDFLWElmYURnWG9X
            OEJOVEM5aWd4c0o4RmtLZVZEUSsyTVUKLS0tIDR4dGR0d2kyU2s2MnJzblB2NWYx
            ZDc4VTVEQ1ZRT0JKajRQTmswWDMveDQKMf76/yHdwuel7dWzCPr20+MwCof2XFKz
            ffcH3RZIdgJlwyZdg0+3gJ6GCkFBB67LS4gbTnF6SF5ZOcQlx7AKtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T17:38:44Z"
    mac: ENC[AES256_GCM,data:OcfyVyR/KOmbbIxkFTLeixJj4b24UUe1q85qteWgZRCiLkF/D0dEuNeG/GpDUPWHFwaBU9/MdBCM3UIMjtq8s8d/rE4932Ymx0z8JbyMCRWaLa3v/P48geiu9AfceNZHsFZcEyRTtEWFpK3z06bK+D1KjE5goUyt0F3LFxPnF2c=,iv:kOyaHiuzK1y4h/x7d9hPAnvQFv+dE5CJEMqqfQ46jCI=,tag:HxDV2v3ZznNH9UhTZpwZkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
