apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ryot-postgres-pvc
  namespace: ryot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 5Gi
