apiVersion: v1
kind: Secret
metadata:
    name: ryot-secret
    namespace: ryot
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LhCu5c2EIflE8dLT6eHPbiKxIUGJKtxp/KtDCkIX,iv:Rp0oAtTVUl5MQQjEcYphMw9DhksAs3Hlu/MbUgsOHFo=,tag:wHY7fGJ5kuV8Joz/ghcniQ==,type:str]
    SERVER_ADMIN_ACCESS_TOKEN: ENC[AES256_GCM,data:fg3tL7epxYKb6WuZFm8SJUb2e4FH/B/FeGciDsWi,iv:bFUNvTWGLNAQqSnocjSmLTYKIpfiKdc0CZR8/osUKPs=,tag:OVVOsJ6poyWUKtkqX5B94g==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:3wBu6Oc/xBfG+ifEaHTCxyqo6TdNrY2mRXCScWoX2UbFsQ7qauePYFA/8eQNT3AVjsHueoU/PK12pEYBWdgvoBPlPtxhiAEDa0p9ziO73Ipj5G9ju1EZ/REDMhBr7cz64k+qTT912IlS58Cpb92rgP1H335VdsX2koj7kgBjZog=,iv:aJfpJPDb5o90KckOpYti0g993jaYndjtbYfrR1Dl7nU=,tag:JvbfnsVIrnaQRN5fdzzrhg==,type:str]
    TMDB_ACCESS_TOKEN: ENC[AES256_GCM,data:xHTq7yHZJhaPK362lM3m2iEuxfdHTGEapc+mMEoA/nQYlOWe9+0wDQPUiXrWj77tywPfYh12VSYwcCPB+w0WdQ4gg5EZxxFHyj1xqYfmVVj9KA7kptfi9O0wU99pvQLHETSGEU4lg+qYSjhdomw+8I+WbiKN+TNProUBVPpMlB/5h6wlio3fF8YRahG6YXA+GmbP5HzX3QY5a7h1XqFpJSHpIzYQYnpRRdSraQOd9XYMz5JC3NmpUuiEV7kJRcuO0i36e7m2do7klNcI6tnNbeFNgOS+j+4weh5xG+YrlZZJJIjmcYrQMt52OhC38Ps=,iv:FxmHIT+hPa/wVwiL4vo3ycMeLtWQVK06Gm4Ug3dN0TU=,tag:UdpI4CNYIQ91rdGdTl2LSQ==,type:str]
    GOOGLE_BOOKS_API_KEY: ENC[AES256_GCM,data:Jig+nw/D0MNmCaUpr9APWMmZ69nGxKomZflgcGS9/S71R4NiXNoH,iv:QCvxaXOeB9E4LbsP0P9+NlxCA52MOB8UHxNhfB8aBkY=,tag:l4AcKvISLQBM/2NyR9kJFQ==,type:str]
    TWITCH_CLIENT_SECRET: ENC[AES256_GCM,data:VHrOihe7ZYG9rU6SoPAt1uEz1f+7uz91IlrkH8hr,iv:kn5P4wHpuif+4MHGNDNphE/MMA+pTGI0p2iD6t/hDBE=,tag:vj8lXpzIgtOLpYO1azwyKw==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRVZuU0t4TE5US1NDdHIw
            Q0xZMk9rV1hGRnJMRHVBK0ViS2pLS0xaMWxNCllTb0lvbUJzRC9kdTcwUkZ6d01G
            QUF2akhZK24weGlvN1pzTm1FcmhSUk0KLS0tIHBIWlF1UUlZTDZmVWdpWEkxTFVB
            QzRBN3gxMkhxRlpmWFFmZ1g1RkphK0EKtRTa8lZbbb0TjzJ90rWaezJt+6k7YckJ
            wnAWX8shC9p0Y/8BQcyNbK7TENpRrWJ3PTm4OOoUiG1ClTG+lQFdpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T11:59:44Z"
    mac: ENC[AES256_GCM,data:S5KlV23XNVGI+/K7GcSifYoV02NqyAMT68mGmEhzyAldLt3F4XykexCi5EhKtb/9elBXGbNvvIIeyfN2a0ykwZDEJdDkm/fh8fXjKd1EYPgEcH9bEpoPDS9XT69aF1FUJP0HVfU6G77pMu7wuz3VB6VLj/aIiA/Ag/DuLhYQLnA=,iv:DoMfY63uXQaLoCsTMi135xPkuyyDPVO5V+B3dfkSaYs=,tag:8FDFVFcVNuQIl8mq8Vk32w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
