apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: wealthfolio
stringData:
    ping-key: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOWxsVGpoZHdmeEt5TGtW
            MHMxQVlnWEU1R0RIa3lGMklFc29vZ1BRMFIwCldWT1J3c2Q1ZHczbGxxZENlbzJL
            cXl0RmN4VG9TdCtGbEZteVNkUmdhbEUKLS0tIEMyaGY1a1RXQW1mU1hyT0p6OGJK
            cWtmSUp3UVMrT0JWd2dwQ01hMGtMSUUK24Ry/f7hUFauMCpw10t2nHLV90yzICO7
            Zi6M5O+QGSADd4Jw86iVLH5IYoR2Akr0hXz6QIXaXVI6t7QG+PLhDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T22:00:58Z"
    mac: ENC[AES256_GCM,data:Oxwl2OPmBshKReM5QJuiZk1G/hlHEmHBcYwOTac7tGVieSrs9jiDAeVS2IAtQfoIzfUCq2owUDQn4Xn5PhanCAMiVgph2SnGiNWnPmFbiCm9+v1+HqyMSjE5RMUvuOdhnSGCWpE/i0LLDadXFf/m1xIpt23/yUrrQELUPzWtdQ8=,iv:8wVAHLeGQ3nwrlkcLJlE13i3elZ/sis6NFjsTGhSfUM=,tag:kJwkfN7jdyaX3cD32HPmdQ==,type:str]
    version: 3.13.2
