apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: wealthfolio
stringData:
    ping-key: ENC[AES256_GCM,data:QKRzfiUNDeXmXhojYmzoc8AqCk/gBw==,iv:Wcq9PIbEb3/0Y8zWkBVkz6KejeveaH4ma9DcjDbNBJQ=,tag:OgK18gBqxtDZcrrsSkoJpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOWxsVGpoZHdmeEt5TGtW
            MHMxQVlnWEU1R0RIa3lGMklFc29vZ1BRMFIwCldWT1J3c2Q1ZHczbGxxZENlbzJL
            cXl0RmN4VG9TdCtGbEZteVNkUmdhbEUKLS0tIEMyaGY1a1RXQW1mU1hyT0p6OGJK
            cWtmSUp3UVMrT0JWd2dwQ01hMGtMSUUK24Ry/f7hUFauMCpw10t2nHLV90yzICO7
            Zi6M5O+QGSADd4Jw86iVLH5IYoR2Akr0hXz6QIXaXVI6t7QG+PLhDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:04Z"
    mac: ENC[AES256_GCM,data:U8RS4cMLELmf6mAQL7ok2FtpQXesfiBC/plWwMxlUS2rUI8Vb5hdleJwCpqoAl31iHv9bz8uoTvetC65n11vth9b2paae3wX6bAb2KaAh0cnOd1CS8E3GqyTB9ye5t+ImQOV5Hlvq7aT9OIiNuIfY92a1t4YuIctnMStHD17CUc=,iv:TeyFXXzN+whEwcfOS9fl/AblY+IIeY3y3UQi/oLyWbA=,tag:qmuTtkPLoV11Ld6INqAGvQ==,type:str]
    version: 3.13.2
