apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: wealthfolio
    namespace: wealthfolio
stringData:
    WF_SECRET_KEY: ENC[AES256_GCM,data:tCqutovjhnNAoKQgsj0guW/+kQwhWECiE6Gcn561MhoGHFdvEOjnkWRXeaI=,iv:31ud1lkfly3GX4U93kWpXSbQbKlSFz/QAeMO3TTbQkQ=,tag:tiIoIWcHos+B8qpv/b/z/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbUlycTJxbTNBT2pYWmtJ
            Y3paQmRWc2QrMU4zOStZakNWNVpQd3BhYVQwCitxUmdrcXVZQWYralFCWUxsZHlp
            NTk2bVFjcU44T2tpNURTcklXYnNLN2sKLS0tIGZhN1hGYjdRZUk0QWhPbkZtZy8y
            THJaOU42QmlkZmZNMWZiMUpkVTE1cGcKhKT0Hk6z4Oe0sdylyg8NL6A1vkoxmM/0
            jT99hD1zxt6xKyak4DxsYgS4gCvvHnhaZNaLa+74BEFUcCAlXpO1vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T10:27:38Z"
    mac: ENC[AES256_GCM,data:C27+ROn5ZrzHXq9OU0Oyln9LxrCdRme0wtfot1Ify38vGDSK2CKGwyqOiZ3089AielnXK62KNoV1bYwrR1dP4VpLMs6SeLlaJX292NVSbgRNbU5bKpq5nxaUmhgv0KigY8FOJ7Ez/y5Qad1D3lW039Nd17OzOrXA1qWmXnrr5yw=,iv:p8GdsbFUjMYJ3MmoAdOo3PP+88wxEL/xe/RH5oeKZnM=,tag:hZy/KMkMSzpJpCWbDx5VIw==,type:str]
    version: 3.13.3
