apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2TYx+8QlrnPj5NY2sUPmt11Fv1CDW/ZL80WF7HA36goOfwimiC3mXg==,iv:jryZI6gCljiuJoMrxOrQvpZa8nUSM6/tgHUJYjRSd0Q=,tag:I6vd1UDfJfrPEJCCbmpU7g==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcDB4Ny9JOEtpRHFMZnhs
            WUdmUUNkQkZ1N0NUdVNvdmZyNTkrc2JhWERNCnNhTVNoaW5JalpCQW9zN3ZwQ2k2
            amRhTzJiU2ZEMFF6OW1XS1FQdTJHelkKLS0tIER3c3NHYVc3ak1mY005c0lqWWpB
            VzVWeXVLZzVlSDBuTGk5Mng1c1BRVHcKdNgKwXKnxSfecEs/dYQm1xuFmmiLRleK
            qS9VNeNLHOlfarXtj+mQHYE/DPHf0vyEF5eIfnNiZUbFzjhEaC5fsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T02:45:52Z"
    mac: ENC[AES256_GCM,data:6/hYiE9Z8YZ3QQUWhxLgOf+etb+B6UTeXhVFnUJT8FmTasJ7AfCH/N/adkaRI2LMMeFNPT/qwVec7ddeV8NCknmQsBDt0jJw7jlQXiRGDst6E7By6l4dnzv1t3hTI1rKtRzKX1rWOejYfIuQk0oznqdh826+bJVed9zkciiv+jg=,iv:VFc4nXvMlB1WXff5P4vGnpr7N1pV9OKj2Yxom77WUXo=,tag:UdjoyL4QA73WrCyA3Gz/aA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
