apiVersion: v1
kind: Secret
metadata:
    name: chatops-credentials
    namespace: chatops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5EZLwY2FbvpoIGHG9q99ge8=,iv:8VI4Gf+RO49aDczf5Sn5QGVvaaFRdZr/mjbRXO8ix70=,tag:D0V3PsRjMSJauTLrcf4/pw==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:8D3vA4vA4cyittkVVZBf4VUw3Dj3gaV6CQb0zJYNbmdmU7mHZSs/kwWlWyBMOg==,iv:QAnED4MCHCaJWPdNYBY8h7iexf+uVbCDy6a5EpduyKw=,tag:245IB1FDncYA81J69xsbRg==,type:str]
    #ENC[AES256_GCM,data:rwe5TmM7kbVznK1hAtPhY+KrIJQn+oV1FCDHKMESM0o/3TvRVgCO/eaKwGzOmkfecg3y9LE1goR8KTUkiY5m2Ya3fcW3+K0mNLg=,iv:SdfQ4R2MeFoE9Ve2X2NwGujZYrvSivzpEe5H3Cxn6Bw=,tag:eD6WnZbmAP2kBWzbPv8mVg==,type:comment]
    #ENC[AES256_GCM,data:3EIwIWOfvCj+fS2+PpzJjoaWweDcFUtjYn7+KSaK/zOgBx5hwZgAUN72T3nMFrh7sw==,iv:aHIJOrxyjHFRuTZ6AivZoRDHGGIbuh3d+A5febmQcDs=,tag:eWxB+RoV9RHk+KlxlWnjPw==,type:comment]
    #ENC[AES256_GCM,data:4YLjxnJuG1V+Nf/GtWSBJg22zes/tz5Z3oP8NCAzgVaDMwK1foCUZuou,iv:D0FuUd2a6NTTdrxPxbKE+/HREYu+my22naZNTs1w7Z8=,tag:wZ9PQxORhX6gF2YAHw6qTw==,type:comment]
    TELEGRAM_PEERS: ENC[AES256_GCM,data:3YDkgbTUFaJN5/zk8Q==,iv:P7xEyjxVo62x+4J9smrws7/ySjBdq/3gw8k9KWtaWc0=,tag:Oy5oWO9XUvSRsGbV4wd/qg==,type:str]
    #ENC[AES256_GCM,data:V7300rPvelnulUIBd6XXLtPX84PjNWnOUr6v+P8Bq0qn/fvv74Mj1OogbN6aOqfdEtT2/8o/rpnzhPz49/b4,iv:bFoZxrtIBh96oNRkaZ1zdyUCLxfrd3rfL6C+2U95WbA=,tag:Wg44p6U69WhYajaeoqHcog==,type:comment]
    TANDOOR_TOKEN: ENC[AES256_GCM,data:s3FMOrPfa6p0JFvT4waKellvR1rtm7T0kq07Cj+7pOlMDsHGFn7bvg==,iv:sLmO1kYGCV5Q5icfqeYvuayxee3Rs8yiKytssU5GV04=,tag:KJjBD9tRzNOfuTbcJOLAgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcWlGS3p6NFVUTVpscjV4
            bXo3MnBnYlBJZGlwTWpxTnVwMTV3Tmc5b0NNCmVBZU9lazJIRkVvU3FNSDF6ZUx2
            YTFwbWJGVTF3ZDNrZ0xFK0czeXVMWDgKLS0tICtuYzJLbmRhdHptZ2N1SVR4ZnBu
            QU1xbUVsS0RoQWx4TzJrcUdtWDBVRkUKIKg36u1HU3Cr5tuCz2wXDYuUypOpJInD
            MCDxFU1/skIhzWrhiZc+Qfd9eSVcW98SN6ZA3XzxHbGTYnYUQw8xTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T15:36:52Z"
    mac: ENC[AES256_GCM,data:JNhBN0Vd990wJrezPHX7TN9d02mvS1SlkAGJUXcfseTfT1H7rNhtlIZog1tnYCmH2cVQDITz2FT1D/0kbiQV0UNwPToLzHg7ztlkfgKG9xWypyUKnLXM8nXfo2Yy27oIerGkH3PGPA8NOVTwYyew8YVxikeciHOZspA38U06ybg=,iv:OwfVmIwvvL56tMj6d8miMboMkeh7Qopx6+grYL6FSjQ=,tag:YMasDjW3sts7ewYEmOkO6g==,type:str]
    version: 3.13.3
