apiVersion: v1
kind: Secret
metadata:
    name: chatops-caldav
    namespace: chatops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:WtzVgn2ljFPeUcehPfmGIEi4iih7eWLsIuCIXd9b3slizFwDQPQDOrqx4ydi1ivvyiFSY4J3KFdqSZeb3Tpr,iv:Xxm9qE9nRUwqLXeVNL7UBBw45KqE+PwvlsnbT9+ksRs=,tag:JsPHbvoOeCI629IqOed4lg==,type:comment]
    #ENC[AES256_GCM,data:FVELHGFtN9c+u2AbhleQafSKLImNuFj1XY8W84MwWzCj8e1Vtu73YRjDv1UVIWCRymWMasiEYxlg69+e9FG4b8qE6uc=,iv:wM6q4RIbIN/k3/h5ZLbZUv6kBPqIjgoLIhNP8lMEHMM=,tag:ZtRw5OL4usBRlIIhL46vXg==,type:comment]
    #ENC[AES256_GCM,data:0/IPZcQT2Oh/+k8HjyPPicZS9AZCvvJbmjesdFmTisex39uKM6ZCBCFFvqAg0HixHXoGBJCflQZOHDiRXqGKigHnNfibe7NsCkJC2g==,iv:ypqjDB4dnUtseYBjTrDYc7P5zPSvpFf6XCNlrIB+mUc=,tag:ppDbTAFtY5lfYq0gvihIhg==,type:comment]
    #ENC[AES256_GCM,data:grsq1GjBMB40+2sukNpxKoOm7rA=,iv:onjFXhoJOLsn4/ccd+JpIN43rB5R+uNmV2s/jMCfQQY=,tag:mNjgrhSRXoTMh3fo/frhJQ==,type:comment]
    CALDAV_PASSWORD: ENC[AES256_GCM,data:NgHbR9Cios7npA/3F3VFZOs6Y3xfK59kDTgQsWtPIjGqEJtBZQpR7Sohw0NZ8ZqG6EAW1RQjj19oBkGYnxCqbdeAOkzTVudA,iv:Gdd/lEVoL5TGdmEZ6I5Bwtp1Cz/Wy+r8QP9mCygoDf0=,tag:5yaP3FA4oTBXx41JW6YBJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabGd3LzBCTzNTdG1raUZ0
            WXJkWEk3UDE4alVIWFljeUhhSzVFVjNZYkRJCnNtR1FGTktPS0FDdXhrblVMRkp0
            a0s1ZUFsMVBueFkxLy9ST3JPLzNYU1kKLS0tIFQ2eE5SN05tVTB2L3JVK0kyRTJ4
            Y1o1R3B3TEVHVXJpWXhZNzJUcGRZZ00KBwcfJedYi1VfwBaXdPzkynqo8fAlBO/V
            MV2YOBQaqvdu6Uc9VoNMnig0w9f9HvwKJIFUwIG7kjfFXb3QdrIA+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T18:29:46Z"
    mac: ENC[AES256_GCM,data:WJXNjQuiQs0NCwDTVpMZ5jWIro4LdiSw/FJkUAQrCpJp/WBJ9EBICoMD4KzhalUaHSnWOigunzr2nU9ISzLe11KupKu43dbspArO9NE5IMBT07R39SgVEausNCcLKFWe1eEwmRoOeVxLzaju/iQI5pDpGAovSpZoNqkuN3K5tTs=,iv:GrrLtUwhJFAZTX5LUaBMlGgD0g9uWEd47+yU9h0Goh0=,tag:bZ8SpqF5AxXgqXesCxHBUA==,type:str]
    version: 3.13.3
