apiVersion: v1
kind: Secret
metadata:
    name: chatops-paperless
    namespace: chatops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:nWg2/C6U6nqGKLrLourUMO/TJ6rxsOe1q8NCTS7lVFENpcexRNBgKY23tB4b/IB1PjP80w==,iv:RN6UaK5JtccP+OMfrS4pE9OkvH18fwqI61gEGvwEoR0=,tag:MePovIHhQJr6ZaAufkFh+Q==,type:comment]
    #ENC[AES256_GCM,data:5ENtdXzpvD5qL5d6dgsMtVDMHakTndFkB62CF3ik2Vf9vwhc4+6kaPQii1MqrJiCtcaxqZcMjsZ38QMQe3BdtjC265Pl0ecxTg==,iv:Ez5anUsQOtzs8PCtb1u51e58TA7W+T7CXS8GA5996n4=,tag:SOeF6QjpeL3KtpXr5Y+ijg==,type:comment]
    #ENC[AES256_GCM,data:l9p0Gg76dVgDBgHcGyR8EyGpgNUblUYgWQr4AOdaur5i4ldYIp+8,iv:52w3C02qPfd1nmosqZSqyVDP1BCZD1Iqnm2LMZgtFug=,tag:L+hogzr8WZOXLlyxnu5QzQ==,type:comment]
    PAPERLESS_TOKEN: ENC[AES256_GCM,data:CrvZA+X0EsT3NVG9jCA1wgyN9A56JJwoNwCGgU6dIli7x5va0fOlUw==,iv:lLp9A4SFMdUUmVZG4KdHl5OXBqzSDmOoToGBHYqM1LA=,tag:XW8yin05LGlhyT4LMfXlTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudzFhZGFuZ1JYQ3A4Qis4
            bThpOFFmREJEMjVuQnFTZHAyclZzRk1lUnpZCmhxVzBvblgzTkhZVFNVYmNTeTBn
            NXQzNG9KM1ZjVDVIdlFzSk1Fb0p1VWcKLS0tIFdNMldCTGE2ZkFMWHRUYnMzOWs0
            eWtiRnMxOUxBbVNKcy9XdXhBV09GLzQKwoJnWtff8YoMiZDS8Lhyhai8u6dEoBkQ
            81h4o4CljC5RnjTx86nTyIE6QuuTVXAhDIiVdu/PmXtQqDZfXA7pmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T01:10:05Z"
    mac: ENC[AES256_GCM,data:/OS+n3RTPtJnKTRSyx4Uuc9s8ikaSS+DrZYetMraWL2SVSsIFTTvLgD8abaqs0DEm01Z56SrSP3dE1gsGTjcKEw0r7nRRszvzH4ax2JAO7fXA5qkQQAAVWY+HwCnLKZeb6j0LjbVtDa6FE1k8FNWGm5/8dZGmMo9smjplVt0TtM=,iv:xF3HqYrVCd/4P0PlpZS4TkPu07KhUJhonk/LiWiuZ34=,tag:SVBbQyZeEpZOwaLQ1DCacA==,type:str]
    version: 3.13.3
