apiVersion: v1
kind: Secret
metadata:
    name: chatops-vault
    namespace: chatops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:pXCHxweRC21EzTZRzgx7br5gQFlNGVZ/790hGPWd4oZ5HBU2VjgFqrzbibMYOp4xcryPvDl1bsmbFAXp1Ml/wz1e1ugd9OV5zg==,iv:Pe4Mw9hjygSob9fcdjsww6Ps7ZnoZeqOfdul4lixEVE=,tag:5z0MNm+EgmgkG+RViWinIg==,type:comment]
    COUCHDB_USER: ENC[AES256_GCM,data:omRlwIE37w==,iv:jPn7fIRdodzud+pdp+h4/WAbh3cd1l2csmJlmsN1EK0=,tag:Y/RLODfsDwF24kQfhWyojw==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:qpFLpdrVEAA0qTBHmDOeheVxgfrPpH+in6hgWlYz,iv:padVjk6Fodcyzcjf9rorNWbNa5g9ua3KCWW134qv33U=,tag:lnb9T2yS+MbCNcXCOKpWWg==,type:str]
    #ENC[AES256_GCM,data:Ab6ywksLTdRzsznW/naZfaDFG6jFee0heKnsCPv5dfKxCjtGPVdTgu1HKOqpViriOVXUddZ1xRP6e5Lw8Sm94Zu56X4=,iv:hOsH5Q6GA8JICO4Uv4e/dAfi8rn7BcHtq2KEHNTgej4=,tag:lPkZTZg/GjwLcnxbtFkT9w==,type:comment]
    #ENC[AES256_GCM,data:rrg3MT7N4vDFb0+TNn9VLwABxBSSIvdqp9fNU7KSiIsx3Velv8bPct2z5wJwLFCy65xQ7/3B+NgX5w4peiUolU03HIy0Jw==,iv:LHxP9GigG4d0cs0cc9pEaTTV/WjixrbET7lMJ8oZEec=,tag:xDxuGVvkwAinTgJGUX3lIg==,type:comment]
    #ENC[AES256_GCM,data:UBjXbdF89rHc9BDYs3EjG02JBXEUrt65evNaCXFUckAV0oYmdbsrTi6yPFvO6YldTbGY9BE=,iv:LP0/hI3NfM8ujHWDLrwHafXrJ6TIBmv6h38rUel1rUE=,tag:1wJyqMFKtDVfrXpdBcpYfA==,type:comment]
    #ENC[AES256_GCM,data:iaKze2FMPSL5qCm+rYxV5511WIgbcN2WzLbzp890ZG5UDglYZWHC3evq7c2ZtK0WLxhkzySKZiRD/rZxi7RWSdEKnDISxtBbtD7TFKNaREso,iv:iuFinW4BWijlmWVgfxz/ryInPpzbCCnxNcS5IR+pL3I=,tag:1bp1c3CzMomdzP2H8a1XSQ==,type:comment]
    #ENC[AES256_GCM,data:pyIYE5O2yI8whx7Me4mr+hy7TpBjldROFJpaYi6IMKcMyr9ugp6l/83PB0zaTG0fIuXvH10C1NpKCQ==,iv:yOE9F+ce+/F9rykamIHijHOjgYWINoTktxl5QqxplR4=,tag:FP060bkUEMozhYJveZ1AKQ==,type:comment]
    VAULT_PASSPHRASE: ENC[AES256_GCM,data:quCaLHYsQg6mb6juJNG6jboReCTXDt+a/6bMZCY1,iv:JCHMMOoWCxeSyLG9uiWGTQBa7KBHaD0me94UTejNxWQ=,tag:S+wF2h3cysdb5Myjyh38bA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNWd2YWwxMmo5M21aMW1T
            VnRzNEtibk5Kc2lYT3dZeWdXbWV5WUpaaEhzCndIOFZkdUpMUCtWK0JNNGV4S3FW
            NHVGZlNWM2FNbFpoeEM1RzdodTZmcEUKLS0tIFpMQm44Z25XUUMrK2lpVDBKakJh
            MmpwVHFyU2FKWDlsVFNIQzh3UGhOZ0kKHB7FHIEStNlL3Hv62ckToNBTTTx+z7K3
            17/5AdQsCedVWhhWCIna03myuL1RJ3V0L0ZHOOy1G4NsGr7AO1HV1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T18:49:01Z"
    mac: ENC[AES256_GCM,data:kliyxBSBABWEYVDDPAiyw4XJm3kEKpHALHd2LUJj4+jE+UBuqChw7k814dAWRI/ED/nN/fBGoNIOlw0kVZRbafUzLLxUUacENaWCQDASGD/e1r5Ra2VKR78aUOA57sHgbK7UaQO2254WDL3lJDy4uTp6OMK0sHZWnJdJlaayX50=,iv:Sfq51q+RUDThnF1Zf0lUb6IVuEkua1hgdOXoWjH1k6k=,tag:hh2Pk8Mx9N5jxbPHRlG+Ww==,type:str]
    version: 3.13.3
