apiVersion: v1
kind: Secret
metadata:
    name: chatops-telegram-chat
    namespace: chatops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:D5jSiYz0lh0lvhqTO9U4+aRrbrqKtc0tNUca59EPhsZEY2kIJMUVqyTD9tXLiSrupsfoyCXVDxZKSq0lQafBJmHqgyUn,iv:OYOPN137kGPXgIrn4d3Tl8FXFsAVHLp314jr6VXGpBc=,tag:fwWpDHUrO4tH/aeRYQWz9w==,type:comment]
    #ENC[AES256_GCM,data:xWe4wMQ4HHJoB8Qp8WfVgrh0KuFfOdxJL4BGoMK/EGtrlQe5rmqzhbG5i+qk/i8xhd5ZA2VwU9E0wosYFdjR3xr4ZnW0i+c6Ze8=,iv:L1tgNhFopopN21CK8M7F7ZNG3/H/mGGj6+kGhr06kwk=,tag:guSHZ3yKhffZzC1uG2HfNQ==,type:comment]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:zel/442IiDvq,iv:YKbPQ8vmGYVa3L/7xN2P8bTmWCIQqLemEYXC9XMOrBg=,tag:U6gN+aTSWqukUwfpUi/x3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VTkzdjk0WDRYUFVEZzA0
            SUVxYU5pb2gxbGYvNjNSUlVxdmExdXgrZjNVCmRNQXJSVXR4eFFjU2dad05ZZjhP
            NE80aVp5NG45d3F6SHpWRlBuUHB5MncKLS0tIDR4eWc2U0xSbEpnbGJzMUFkNnJ2
            YWpUUGdOSzNtNFR0ZlhOZ2o5NFI0Rm8Kqbhkuxir52JoQ48pj263E60XI+sIZb4r
            cou5H+81vsnzvO4cc6iHffwfRTdy50jI2FrtCFvMLoepZT+4G0wqsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T17:59:04Z"
    mac: ENC[AES256_GCM,data:GeGzLT/Qc4pp0JjceQ+tq0HfNfk4QuxcKlbJ5cawa2i5Ry6L1vKl+Jd9l1faPUF7gUoJqbT4yKVV1HL6SUTA2ugAVsrqNgNnt16lFeknhHGSXAvE5sb+WMnsmtphyhDEvfdUB1mJQJmlP9vk9N3lxu16HGmBUbL+ipl+v4BqLvU=,iv:eyL/EjQiYHcY/+47x8UQHt74EGhriZXKIkK0a6UYV8k=,tag:+AToqDuZA2VmOZCSfzBb+w==,type:str]
    version: 3.13.3
