apiVersion: v1
kind: Secret
metadata:
    name: chatops-credentials
    namespace: chatops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5EZLwY2FbvpoIGHG9q99ge8=,iv:8VI4Gf+RO49aDczf5Sn5QGVvaaFRdZr/mjbRXO8ix70=,tag:D0V3PsRjMSJauTLrcf4/pw==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:5usICZ6iNVqnUg==,iv:VxeI8UUy8r37l+mZxyiGaWokvEjbrvNFLVxVDWlVy+o=,tag:lSTTtOBVnkOmuTr9WjHD8A==,type:str]
    #ENC[AES256_GCM,data:rwe5TmM7kbVznK1hAtPhY+KrIJQn+oV1FCDHKMESM0o/3TvRVgCO/eaKwGzOmkfecg3y9LE1goR8KTUkiY5m2Ya3fcW3+K0mNLg=,iv:SdfQ4R2MeFoE9Ve2X2NwGujZYrvSivzpEe5H3Cxn6Bw=,tag:eD6WnZbmAP2kBWzbPv8mVg==,type:comment]
    #ENC[AES256_GCM,data:3EIwIWOfvCj+fS2+PpzJjoaWweDcFUtjYn7+KSaK/zOgBx5hwZgAUN72T3nMFrh7sw==,iv:aHIJOrxyjHFRuTZ6AivZoRDHGGIbuh3d+A5febmQcDs=,tag:eWxB+RoV9RHk+KlxlWnjPw==,type:comment]
    #ENC[AES256_GCM,data:4YLjxnJuG1V+Nf/GtWSBJg22zes/tz5Z3oP8NCAzgVaDMwK1foCUZuou,iv:D0FuUd2a6NTTdrxPxbKE+/HREYu+my22naZNTs1w7Z8=,tag:wZ9PQxORhX6gF2YAHw6qTw==,type:comment]
    TELEGRAM_PEERS: ENC[AES256_GCM,data:FlJgYg0=,iv:gZbOsBErRTEivENgiKbHMyQ1inSopeOOfQ0bgQCzXY4=,tag:8iHUnJEDroQyTaKCiea9Bw==,type:str]
    #ENC[AES256_GCM,data:tFhpxJ6b1UdDdMzbcLDx7wo8ZHBHcA==,iv:XTmkPKf013Hxx+7Z/qPUN4hNgS1iqc4IfPl+5adL5iE=,tag:B2S18kHJD1yI85NY2phrsA==,type:comment]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:yqtQPFhbcVh8Kw==,iv:TQ+GRkpPKF+umt+bnIdrREiK0qEJjcLE2GDca08z/Wo=,tag:/cpYrkjXySSYtMmh9JeAIw==,type:str]
    #ENC[AES256_GCM,data:V7300rPvelnulUIBd6XXLtPX84PjNWnOUr6v+P8Bq0qn/fvv74Mj1OogbN6aOqfdEtT2/8o/rpnzhPz49/b4,iv:bFoZxrtIBh96oNRkaZ1zdyUCLxfrd3rfL6C+2U95WbA=,tag:Wg44p6U69WhYajaeoqHcog==,type:comment]
    TANDOOR_TOKEN: ENC[AES256_GCM,data:8xlWe6/A6LRIlg==,iv:LFl3qrt0VNge2rLcnja8FCBNyf7JaTuxVyC5Z6vB+aM=,tag:2xWUYZ77ZQ27PbNadOxJyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcWlGS3p6NFVUTVpscjV4
            bXo3MnBnYlBJZGlwTWpxTnVwMTV3Tmc5b0NNCmVBZU9lazJIRkVvU3FNSDF6ZUx2
            YTFwbWJGVTF3ZDNrZ0xFK0czeXVMWDgKLS0tICtuYzJLbmRhdHptZ2N1SVR4ZnBu
            QU1xbUVsS0RoQWx4TzJrcUdtWDBVRkUKIKg36u1HU3Cr5tuCz2wXDYuUypOpJInD
            MCDxFU1/skIhzWrhiZc+Qfd9eSVcW98SN6ZA3XzxHbGTYnYUQw8xTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T22:45:22Z"
    mac: ENC[AES256_GCM,data:JzmDGRqBnlnIh63aTDtrA8/YQbPQUmKJ03CAgHi7jxeLkKJ3NX2Bc42WIClPm7P+Z05w0G/P0k/CNgEo4EYB5mTdGB5Nu/gsBgJMEC36HAnt3oc1ApByQS7inFUktyOOkYtikpqQYw/RCinAAt0XfC2yntIqF4gneG7jq9EvuXc=,iv:cxNxNCeGGBZVqLMADN+TnKVZM1Phf8yYSEvE49kNn+k=,tag:RMlp72FoZ83q3SeXx9QQlA==,type:str]
    version: 3.13.3
