apiVersion: v1
kind: Secret
metadata:
    name: chatops-homeassistant
    namespace: chatops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:pGV1NF94xNxXrecWHbVtWFV1NeXsSA7QxPDNoaO0BddFbqt0zRWxGqhTBeAGOMdBMcUbffvqb9PskpKQeMy/Wj7l,iv:TCbmJnxfpaWvrnr0dQkxlEpldhIb94FMRKHiBIL/luY=,tag:qbYREYiNAUPCbG/kCraQ2g==,type:comment]
    #ENC[AES256_GCM,data:+9AuoInswUkeOV935bxOj6mHNaDMYs/wL8H/3YQdmeJGs0RYSfhS68dk6BDbzqfe4QzSsbMWs/iCDlARSCyde3l9pPn3ZQNaE7Hh,iv:y00mKDoGZBHRy2Y6xoR7PitfPJeIAYUVcYcEGsuTy2U=,tag:/SRST7ykEZEuDaGoMFXsHA==,type:comment]
    #ENC[AES256_GCM,data:DLqkz/tuli6vitNsRqiVoWrgE3NL/MEYN+B7pda3GQ2eaGNPtYBD0pm3xYTsN9QfeU9mXUeuNxar4shgGH+a3pRxf1azrb4HXLy0fH3VuGESUoU0/Q9+KpM=,iv:zteYEg0KAnt9hbMYdZhR8hZGXE0EmFYO+DOCdr47iLs=,tag:cpcD3YXYub/lOJHRfTjjuA==,type:comment]
    #ENC[AES256_GCM,data:2gfWGGnUwTQFdgYSe3YzbiakeMsiXwzH0SGnoVxRnVS+AKgznHT57+AnArEB6o8=,iv:KcoRaR6NXv9andCkf5H413WDh0NDKZclkNhg3mwBdf0=,tag:7Pf21gioUH45Ds3Nuj0U4Q==,type:comment]
    HASS_TOKEN: ENC[AES256_GCM,data:V7zc4vq+69fuUQ==,iv:/29yphCtZ7eg21fifeAWmNFn7xs1jCHDU1BD8/byihw=,tag:ZjWpgVkdD4Xm5eCIIt3DDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa0xuNEsyWGh6WUdrZEU5
            UGNWa2V5ZERzMDNjLzFzSnlRNlJkdVFzOW5VCjYzZHdRY1BTRmxXS0tkRmh0cW1X
            RU85Q3haUFlmUng3emxvL3ZzcFJOK2cKLS0tIEt4cmsxSVhtVDQ2SVozSWNqaklP
            Uk5oS1l6WTNyU2ZuaVB5NVpUdUoxYVkK88+sPSVvUMUDV5UZSp5g6+XWCrTzih08
            qmWRuE6JiIPSusgbbRkGgOmNbnTI6b4iMQOrDPztINmgSnzr2EBH7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T01:10:05Z"
    mac: ENC[AES256_GCM,data:T6fCyWXW2pqQ6EV1tgbilUmoQTQZ5+dJqekgUvDhxrvPkSEk3rSImu+Y6JsdzQGiGtmTGL6KETzpmWrZ6Jq6NLVHdfolowxDINhEUiYcCWJqGGq6ACIS9ZgNoeb4iZnf08b1oQzkkX6mWNWajwalZz0m9qUk4LOr5R9ILuLYC+8=,iv:bWQ7PxoKR8bL4sr5bdg8iaU4Z3MU2aVsuDkkxEOfXMc=,tag:PiS2adCYNIxlV9jCopt5og==,type:str]
    version: 3.13.3
