---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-config
  namespace: jdownloader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-downloads
  namespace: jdownloader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hdd2
  resources:
    requests:
      storage: 2Ti
