apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cnpg-b2-credentials
    namespace: multica
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:O1X9cTVgBUr6De+PqW/8KToy8ZSGYq9cUQ==,iv:hmGqyXEBFTPjJbzjMzR94wmbbxRXcZFRfLHb8wEHTZU=,tag:+ZLX7ONiHHRvq92OtHlZHQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:gKoOexhm34sne1QeFrhoVZOsm6YRz/de66POwFQEqg==,iv:IOEGN7VjEeh3mBwYTzfpJNyoUpIiEKM9siMTEsBzyV0=,tag:Bi8bmcqownTZouYKa/YbqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZGdXeVJGK2xBdHdLVWYz
            Q0VUeHRqbXROai85ZXphVWg1dGRjamQxelNRCllCZmwxaFlJMTNPVnRZN0xWZmRN
            N3JtNmNNMkhEZHFsMkt1V3lvVldhOE0KLS0tIDhKVjZCVEFOZnlUNkpJbjZhUmhP
            KzRaUU9sNk40V1hZUmd6OGUyTUpJWXMKmmjzgaFWAESD392NEQh2wu0W6Y7c7biA
            DtEavlC7vALXrGzPwNKcd88TbDT1YPphEHDSuEkjoF2W+D5juzMpXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:38:29Z"
    mac: ENC[AES256_GCM,data:BtmYT6Mn6kIdvxmE2SzmIInuhkj340gU/6ggs0OIvIpJUHG0XqGP08VX0HQFRAs1a2MmGztkOuCaoAFPzuK6TV3sRZuIbcswV/tMyeZ4WwY0CWaguOBZDclgXV/J7DRrzXmuuLU68TqhJ0+m7jJXTIgAwRfNC+azCylcBqzl6q0=,iv:PAzG85tkmkiHtd9c5smJQushbgT01upHCKo/SRtNR3A=,tag:DJs7b9nws5ztk+9ZM0dT2g==,type:str]
    version: 3.13.3
