apiVersion: v1
kind: Secret
metadata:
    name: multica-db-credentials
    namespace: multica
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xBeDQB2DWA==,iv:o13uTZffn78sNuk6f3+C918iHmEEG4f1HARTHRBYA1Y=,tag:O/uTpuB3qELXnZq07AVQEA==,type:str]
    password: ENC[AES256_GCM,data:5NFRmp7J8C8bymAFJB+IIFatE1o3FrnGPA9lKF+adZQ=,iv:DY/dbNXU6IR87OzEJiIRLqLmTQpDgzRByWjDjys+tE4=,tag:R8kl2I/k64cCZ7jx4CU4qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSkUzbzc5R3d1Wmd6OTlx
            MXUxZ3NrMFRsdXF5dW45dm1EYWg3MzI0a1NFCjFFcWVBUURVVVVQdUp2Y2lqSTdZ
            Vkp5Y0FTZjVjNGJlcmQ3R2tFaEVkV2MKLS0tIDFyUlA3aGtiWUxQT0syM09DNzFV
            ZUpiSnJrcHlKVWdnVjFHSXZHYkNWVkkKHiStqn4rQWEDiQiQaBuhiasH4D1nsbEL
            p8Wxs7RLBKXFMTU+cWhJ6WOnyTUl7k31AX8Jska9aTZ6mmnci0AbnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T15:49:36Z"
    mac: ENC[AES256_GCM,data:srmRBw+cC6+9A1WUAZOQaQOerJZsqFxOPbQZMv4Kli8KdF4EC5yd3CEfAqYqiz4qHYMSNOagxSUhQ/aioScV+nFGhnOgScLxQ7OgV1fuIQOHjiBClUuqrXN1Qywxn946RLMrsOudjImWW+jVQsF3W1yJlH4Ua/bM4NtdS/smNR8=,iv:tCMUDkpFgkeAT66lroM3mTT55KGoEGya/mk4+xN5q9o=,tag:q069AhDKH5HDyZHlas81rA==,type:str]
    version: 3.13.2
