apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:SFeT06rBA0oN86d/LCQKEtpOlQwHdIMtICcYxf+Crv3/KGvjXpiLQL0DLz6bDY1jXuoqaoaSbS9ol0br,iv:HKdgX745s/TAmsNJUSrJ3XHXVmcvjeWSoWvTkoi4+tM=,tag:ZG0EcPeKG/t8+aiALYfJIw==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:ETo0Nl0gLzgQBT8Jobne/0vC7bhwkkm5XcvMO81DeHMC/VJNbQgg5L4q67yDAZ9gUlcSa5yBVsW5hOn4,iv:yVEKv63CXi78jKyPxkPQmfsWmFjl9EiVFxwTIa9qIJ8=,tag:mvJgQW2B8TzcUsLcDDdTdw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Lz90Y3bcBbvGFB6Q6x8/jCZv7mkMGInVbOM6sQhd+n3VMGNVdxKG9Y4yIFVnu7y6EPkTt/8RuIhu43wH,iv:lk1QPmMe6XTNytji9+ljxAkKiPrj28UIFZ3kZcehhY8=,tag:CE74wCnOOzjFuDM0sp3cZQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:VWpw5q0=,iv:t6zha6+KqTdOF3v8IfWxopAyoraQnG79Qqhr1ewewtg=,tag:azfi2RbIK9aA9Yiurtp3BQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:3jtQTph/OeCvfEuinvlSCdZyt0RVscvpu4wHLbkg,iv:DXvZ+oskRK8Zzhz3eYm/mlAdSidA3cL+FLReka220qs=,tag:phMjh3aAaXnFqN7IdT5xcw==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSzVLYzgzZlp0WVRqTVBW
            T01XZUpkcHJxdU9BNVF3TWlOK0hFSDRYOXkwClhqclZSSDJsUlZNdE4yUkxKMkZl
            VkI3aHpsWjZBZzk1aVQvMERlUU0rMFUKLS0tIE9tMXZQV1gwN2VhN21YeVZJQmcx
            eGRVSnJsTEpvU1VFOFEwMXY4NFNQOEkKGdWopO4zuC2LG32qEBHZLB2J2lHfUuBH
            veMrZ0bQs2KKABu7ZvwTDSykac3KATuS/CWSv8FcjnccBRqGFmqYmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T21:06:57Z"
    mac: ENC[AES256_GCM,data:9Z6uY/fAeUyAuc/eOSoNT6pwlwOEfvpSSnEPz8Bnt6OrNNL6N3zkXL0YpLwW1cfY61vhDaa3tCSyUfBB2N8RFvgiJdatzvwbMIYamvxiO50JHIsoF1kZFY7myV6R2ISgyFyeKg6OyU7fQ7zTfVUO8mfljjwADwJT7mOjTlPfvek=,iv:Su4FW4xfenhWzBb/wEMu2kzxii1Ah57Ng8QL2hrssxo=,tag:8Z0BRGojP6QAt6pUpkwmgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
