apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: renovate
stringData:
    ping-key: ENC[AES256_GCM,data:K7VoDIOqYRoi3I8xsG/RODyg+0oMHQ==,iv:PlUg6FbtVLdRQvsMbDsAOvdIyi0YO6Nxucj2NOWF5nU=,tag:CJsFssGN6ch53/oqlsscMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bExHM0VXdEU1QXpWamtz
            elRHeEZSd2huZ1lnT25ETkRueDBRd0Z0MUFRCjdqbk8wa3ZqaStSbFA5QTRLK3VL
            QkdjV084RGZXd0I2VUQ4MEd0WEdxRmsKLS0tIFBoRW14b08wczJnT3Z6RXVJTjk0
            MlN3ZzBBalBGaFp6WFhkdkpabjNUS0kKwzd2XFNECW+zgeHHUnFlg7k93C6tOO+k
            /LvJ7uFCUhlyrP0nk/ZBIRO7Yl6CCBEr5Ox3smZLBmzFlDxJS3/1sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:04Z"
    mac: ENC[AES256_GCM,data:LM3dW1I85VdPEqeFi8fKdw4RYhuJpJX19nnKXzS1ayB/9OoaOJw9czkH+ZuwxkOf4p6S9j3dw5852Xd1aMqr7FqK2UOfVqVHplfZZ4ORmdrvSNLaMq6i/qWxUK+pb9e5LPpOlptHHR3omQ3dTvPC4nxlJBfrC1enl8x9jHZZ1Ho=,iv:yd/Hh2p5ff6uV/LnMXAuW+QVeDQ0Y9XEVEmwGIx01sU=,tag:2KslLxHo1YCSP9UuiKlVhg==,type:str]
    version: 3.13.2
