apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: renovate
stringData:
    ping-key: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bExHM0VXdEU1QXpWamtz
            elRHeEZSd2huZ1lnT25ETkRueDBRd0Z0MUFRCjdqbk8wa3ZqaStSbFA5QTRLK3VL
            QkdjV084RGZXd0I2VUQ4MEd0WEdxRmsKLS0tIFBoRW14b08wczJnT3Z6RXVJTjk0
            MlN3ZzBBalBGaFp6WFhkdkpabjNUS0kKwzd2XFNECW+zgeHHUnFlg7k93C6tOO+k
            /LvJ7uFCUhlyrP0nk/ZBIRO7Yl6CCBEr5Ox3smZLBmzFlDxJS3/1sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T22:00:58Z"
    mac: ENC[AES256_GCM,data:i0iQ7mpUEDrD7H0BnlnR4uGVbHfB9yX9sqJNQHXiSM1IM1sxFx8Q0BmtnwxtO2bfuTmhFVn0xy/GK/V0B1s6AobXLJpEgWtvTVuYX1+tB+fYegd+2/rHucvbxUpMwqG4lHpd+dG3EKIu3Mt8cIwPGcaFVv3GPJUB2BCJWCkRGmA=,iv:RBFVzyp7KeEHZFsiXRI2x8Npa6XPmqh+JiS6qlJ7uy8=,tag:bLIm69FLxn+O2sM/ytnd3Q==,type:str]
    version: 3.13.2
