apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner.yaml
  - adventurelog.yaml
  - chatops.yaml
  - claudebox.yaml
  - excalidraw.yaml
  - fredy.yaml
  - gotify.yaml
  - grimmory.yaml
  - home-assistant.yaml
  - immich.yaml
  - jdownloader.yaml
  - karakeep.yaml
  - media.yaml
  - minecraft.yaml
  - monitoring.yaml
  - nextcloud.yaml
  - obsidian.yaml
  - ollama.yaml
  - palworld.yaml
  - paperless-ngx.yaml
  - searxng.yaml
  - slskd.yaml
  - tandoor.yaml
  - whisper-cpp.yaml
