apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cnpg-b2-credentials
    namespace: tandoor
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/cX/SRolsjj0TSvEr6Gm+nT+bkqQRnfy2A==,iv:SVkyTztvWGpEoyCgHvZ/cCgHMYktUuosDwbbCsFCkXg=,tag:N6qKavwoK2bjT1rhHWQtNg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:zaBco+nXZmnPrNU013FAbmUL1rHTs0VCBel9KlNZ7w==,iv:+d40k98bxtp/VoMpPUBxKdqwPIIfqib31LZbQlZ5GZs=,tag:qCuudekfhFHEOHuX15wnIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeXVnZEJselRZWDdndlFH
            YmJqdzRDWlJlLzNXamVnZno1c2lBY0YyRmpzCkhpdW8yOVlpQTdENW1OYUFKaXB4
            UXBIeEJVdDAyVEttVlNKMlFUaVdVQlUKLS0tIGV4OVNYQ0pOdjNzdHRTcXd6alI3
            Tnd5R2FNT2RGN3RwemJRUjlVdTBMK0EKm3f1vR+vVs/KlSdPXK8JWhkpJMc6qKJ3
            PISss9Fcaa0tRGsdsy2mjmiCieZybBO/eQiYjZeJQ6+jEYX4FlVxrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:38:29Z"
    mac: ENC[AES256_GCM,data:HOEr0AJseDIum7NqXGwtUyNc728jrkq0wHd4RbvSzVqkNmuzh9heovK4PH8U9KjErtqnXQuPGM1XmRBtgX5AlWQU7/7vWDJlrbuY3l+6EdQ+KgfVyuc3+U4UpujoK0a2PD+SA+jglxfgdKS81KBJ5b8P9c6pSnKvzWXP/z93Nqk=,iv:52FsCE0JpHMbl4hbBJaYE4mPLoaSHABPvWjFl0YsrhA=,tag:KgjcKl/RcMnRZv4tw2RVbw==,type:str]
    version: 3.13.3
