apiVersion: v1
kind: Secret
metadata:
    name: tandoor-credentials
    namespace: tandoor
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:nGgHB/m4U9nX5kGjOKsNcr9vtURTT4FUg1AGRkdw,iv:hziTWltW6Aq6yDODwqUQDipvCrwvI1Vih/aV8A2nkeM=,tag:bNyHuiTov2NM11PRB/FwBQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:64RgRaaePbDHkd2Sp6ekqMy7a59DqikOYFUAddIeSdBGpVtu9zS/41w1IcSMe4n/txv7bmeJZxgmIoRB,iv:DlnvDEmx7OuKGS8RIs1t2PCeWlDEHcFzXUXoYSSm4Nc=,tag:jWoON+xaqbKQDCKQ35R32Q==,type:str]
    username: ENC[AES256_GCM,data:2rD/9exUaA==,iv:GUl7ThsmRegz3NJrDwX54lHuM4ebbVOZbLA7cYMaxXA=,tag:/TKU4fhASAC7aSYscKWszA==,type:str]
    password: ENC[AES256_GCM,data:01r9aAIo293LoRxP+YlYQIrl4CxOsQ2/WgsJ2RKu,iv:KLC3NnFDEmGD9Nchjrjqdec3mYgjtzXrL9VOoe/2WPY=,tag:jq2VCt277jGOIc/x4D2EOw==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL1ZHYllRSGgvWkZBS0xl
            YklZRU5sRExsRFNKYXZYa1dpMFF6M1dvVGdJCllRSlREZFFyU3R6WGtNUnJjMDlQ
            M01SeFhiNC90T0hjWEhDcVRIZWNtcXcKLS0tIFk1TzFRZjRja0pMVmVtY0lRdWMw
            SDlPSkcvcUJMVlRmU2ErQlFkWExCbFUKCV8EU8MA15Yqhju4STmwEkbat4sIJWWx
            UHfGBZEEqtW4ARkqALNdqwmJlnYFGDwl/GeB/+/+fQywfnrS9VNPww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T14:05:53Z"
    mac: ENC[AES256_GCM,data:hFUQzug0ZQsFVhzmO/RWvTJtRYMEeyGcug5qpFdVU1FtY61HgLwrDW3vds2FfQusgoyrRHBImV9u3C/YPNVR7mwuYvxPxJGdbeg6BrNohMXz/FgI6em1hhL7cMSnBRBSnTjcej+z1b7Hv4f9hM/oxIUhS9UHM6BduBzkjbi35wU=,iv:RQ+b+DuxXLddUk0LIzXhXPALxio7kTyU9JFjq/XzKZ8=,tag:1QNFVibCQu4RtbdrqYcxxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
