apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cnpg-b2-credentials
    namespace: media
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:V1aQi2p5w3KGMuQcWmlz1kjr0r5pGOFfng==,iv:ZkVmB7p1NJozwlROEouC4snXGMd7inV6GRmK9VWDeNY=,tag:7GJoPPGDWN9qiUrcD/Wrvg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:e2Xzp/Bcaes+flBFkK3PP3VIFM82Dl4qZkyOZsvrkw==,iv:43pQD2WfzxuIiVR5lvleIdkps7O7cbaSpI7raR/IEG8=,tag:pDqXHUtwUyqeAR/of/4Mwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Sm03RVBDZ1NtTEh6QU9B
            UGVURCs0cjU1YWZlUDJWL1l6UzZ0WkFvT1NZCnZiMWQ3cjZtNWFZYmp5cVFENGFB
            emRNTzBVaXhGZ2k0U1EvTGtYRTdpSkUKLS0tIFFPR1QzSnZIUHc5UFg2Mjg0QmEx
            ZTFwaG1GZXFSVzFVYUtyY0VybHpzMVUKfZ93mhRYakE+9MZjwX2313iJhDNenSWX
            1Z8+K+qQcfvfy8BdJtCwmnN5Byf/5/Wl8a88u+o5Ql6gpZ8Ya7nHww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:38:29Z"
    mac: ENC[AES256_GCM,data:rYGet7vAe1R/01gw8gOMy3mYd6Jx6FTTtkdQrtSuVo5K3Zvz2OUx2sFieIRUlCtQYTVnCHbLQ6E34tz2F6gzc/SM7g3GseFX0rQVQFgRx5CBFJZzUqTyNDhEiW0zsetuWJZ0HW/ug3ywpwLZf6y1pmHDKEIDihALupE3rFoZI+w=,iv:zuhfL+VJLtttAQ56ZjVnd/h38F7uAWwv4+3IFgG6tFk=,tag:XHkJzzoXiJ85JCvkCf086w==,type:str]
    version: 3.13.3
