---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-data
  namespace: palworld
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 40Gi
