apiVersion: v1
kind: Secret
metadata:
    name: palworld-credentials
    namespace: palworld
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rvdN1Fg/uwx31mJp0rEfHGKFiI4bNYUXlVJ2foY6JGZu9z9TPS8yM1g1LA==,iv:QXiuDq3PTtWmcf0ygJD3Vp73iAvLbpz3WH4DdQK2FUY=,tag:Kww9uIk07IWkZRD6f9NoXA==,type:comment]
    SERVER_PASSWORD: ENC[AES256_GCM,data:/X1JnjIC8ZTJuOU=,iv:L+/NrqP2iqlbKqU6quuArpMkvMF4X8ZrtV3PEZwhwPk=,tag:/67bjwjFfmVUPhMH02FJXw==,type:str]
    #ENC[AES256_GCM,data:7axDwmKglJk2zh34L/z03wHnrlKqxtbao/B1YhOfljMxtIKI9GqxjmrXjKBUBrZGjAFYmyM=,iv:6lV8yy2R2iqf5MsmFvUsxjvppNnEqmn80Sa0GdgsMeo=,tag:vbLT+DjopzdH3hrDiqQlaQ==,type:comment]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:2Gjf2YLEXAiXNFM9CLg=,iv:zFknqoZkoXPFedxUHGHklCHL6SzXJgV8YFJ1/uJsfRY=,tag:fzajy2PdiQx9grPGM5sexQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZWtJd25QY0FaTWhNeUpG
            SUp5L0JKazlPWmZFNW1hTmJrZzF4UUFlQmtJCjVzUTMrdWFvYkorTWl1blFZQmNW
            L0lpbklaZjRJK2lRdjdGQUFya0ZVOFUKLS0tIHRTMy9qdnA5M3Rtc0ZyZUJJSkRW
            eWJndXE1Y2FvcGNva3JhWmdWSWltdkkKkcwwiUeWTDvSdPtK0DVaZA43858auOdS
            Yj/+EbtMviNrqw1ku3iS/7r38rNS4NH8qQUGXPQv1Ro9TnK7aXisSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T16:39:10Z"
    mac: ENC[AES256_GCM,data:vmJX33AIKkBjGgNZ5DiI438JCY5kcg0qB95i9OQtJFtA3L/SnbA/xk8FSzoOm/3nxhl+g/DfpYvW7nePTi6prdL/d5WXTbSR0RITr6iXDEGUd3LwHYIQslMSi1M0Nzj/5J155n6nY2hMZce/hpqUAY+h3DWQB6NSJg+P2XQwjRU=,iv:snep7TFDERUl+HMEzrjjF3UIwZokQVSqgrOILBlzVXY=,tag:q+q6x40k/RuNbiqtt62xjA==,type:str]
    version: 3.13.2
