apiVersion: v1
kind: Secret
metadata:
    name: protonvpn-secret
    namespace: slskd
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:lFMMilSlStv2YPjK9aBggUcNpQULx+cxsBul/ptzt1hbWtOn4Ipq6d7vrvU=,iv:Ox+30TWF78lUxXzHC3+yWdP+SfSZI+gM19u90sQTMPI=,tag:5w8VT30KL2mOm/iaxMCdDw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:73PnaWMVQhE3Kcs=,iv:J8Bo6qGI/IMFPxlv25OD313cmCUTKj1vGhRAP6S1tp4=,tag:tS9R2Kj6Gia/oaw2f1NWqg==,type:str]
    SERVER_HOSTNAMES: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET0NMaGhIblB6dkhaZlJU
            ejMvTlhxRENJU0phU3ltTnJTSFRUZXJVOHpBCmZSdmVqR0hENzBkRStLeEhSWWFn
            T3RnbnQ4RDViTnBuWnE2TFF3RElPNGMKLS0tIGJRM0JON1ErVGZLQ21KM1E2VXQ3
            RXQ4MTdDUG9ySnhMUnFEVXRPRzlYbDgKKcEiQGBKQfxl7yhwEd9CEYAtz+N/zQ8T
            nKWpIWz42DlsgI9CsvpNBjXWylvaMkvTmbMuinjQdFnfTbQtUUDXbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T22:25:02Z"
    mac: ENC[AES256_GCM,data:g8XcdZSpxsiZsNWNxAx0wG8DxdWPeesBeLG8NtcXcGghaUbJm1JvKW8QWfnWWHyMq4s++Fs3VJkn50A9MVTroM8zktcbmfKCjrr7+52EPPczOMxK5Um7wRcI+DIUB8MHfXjK8p/PzuoSm7Ks+vXG/SKzTcVKjZyBZaXbSUM80Vs=,iv:wJKZTGIxmSYWNKNMvhKe9uMrJxEOmDRXyXTo+GfFMaU=,tag:DesS86cA1CbaKB7xbp7zlg==,type:str]
    version: 3.11.0
