apiVersion: v1
kind: Secret
metadata:
    name: soulseek-secret
    namespace: slskd
type: Opaque
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:WO2P5RH0YLEYJCx/Hw==,iv:jSLW7wHAu++zWev3kducQ6BJ7qbY/AVE7eV1t8Fvbxg=,tag:FExDMdxjzSaztlaSKU+tsA==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:87dlmZ8I9D4S1WRILRX00JPUOdc=,iv:o75TCcct0fdKLsmTtiqYQBEj1ELSLRUXFnzDbR1YNFg=,tag:SucZXvTV7zaxVzIWHrVMlw==,type:str]
    SLSKD_SLSK_API_KEY: ENC[AES256_GCM,data:vKWNq7gOUKndVrLAEUdrrC1DNvhm53d0mlIet5aI,iv:Z4HBoUqK0KV7pNeZq4oizr+zFYMKpivUu00UXoN6G5I=,tag:5eCl63/hpzUc2O9B2Oby9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMEZXWi8yNXpld1cwNTBL
            cWZwemlYK3BpV1dZRWVwZm1tYkZ2M0l0KzJjCjZTWklGV3h5MVZzTlNJTzE4a0hH
            ZjVVWkZzOXBKaFc1eWZPbGhDKzVHZWsKLS0tIHRmbjVwbUlyNm1Fd0JZeFVxUWFs
            a3BzOCs2ZDBYbnNTRWFDQzNhQmtiYncKWNThHHjQQl02eLHYCOn9gMOntqKGoJy8
            HTgqrg2VSQWBVl9TMLKVjK+3qs0w7JnK3Rznd++YCwH+6crtitqxZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T22:25:02Z"
    mac: ENC[AES256_GCM,data:yBeLLe865WF3tGAR+k93XRzqHgERF77KCpNF+ispceGU2DM9Q1NnW9kRIdWBoJtiC/O2I09Vc7f5rk4e6HohvFgLRosf0Wb4geC1VT1gowws1Z5ZcQ0alrw51XMp/BuwSeVPzDO0CLUsyUwEGkiJdIdV27Gq8RcPPVhlJK3utZc=,iv:g3vykfiepGAiM5jluRPIBBi28DZWcFYbz5zbiw0xAbw=,tag:6EVlUFUzft0HqiGX1/sV/w==,type:str]
    version: 3.11.0
