---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sparkyfitness
  namespace: sparkyfitness
spec:
  interval: 30m
  url: oci://ghcr.io/codewithcj/charts/sparkyfitness
  ref:
    tag: 0.16.5-8
