---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sparkyfitness
resources:
  - namespace.yaml
  - secret.yaml
  - helmrepository.yaml
  - postgres.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - networkpolicy.yaml
components:
  - ../../infrastructure-config/networkpolicies/allow-from-homepage
