apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-postgres
    namespace: sparkyfitness
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:fgc0kUKp,iv:83sPaqf4OmP7utWk8IJJcgq/2xQcy1LolrIj0sqKSCM=,tag:KXeMizWobWBzVJbRXZxByw==,type:str]
    password: ENC[AES256_GCM,data:Nb9A+KXsDnpFAAn0ZpDsRl2k+o9ZcLZI4NksfW40Ksw=,iv:uQRatSYF26c0zby1bquBQiFCMZ848lR/pplgoAevEiU=,tag:2ZXVE83GQZ83mb/L6wEp2g==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3V1B5ZDVkQVRVdmFFRXRT
            emNFMVo2ckRNN1RQQmNNUXBETlI3cC9EQm5NCm56U1FwbkZOdHdiNUEvbHh3SDU0
            dFQ0bWR6NGNjNGN2bmNMSUpGRGxvVmcKLS0tIGhLbCtuWkp0Si9Nc3crTDFSTjk3
            WmZ2UEJhMG9kV0R3Y2tLdXJCbkJUdVEKnfRt1+Xfm5VHPa9U36BwriTTnwb4B/MZ
            Sr/d/ogibhmmei1OK9uItL0q32s1Vo8Qe9I9RNcE6Wenra8TtzOtOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T21:38:09Z"
    mac: ENC[AES256_GCM,data:GqqUIuqzDFukJJQMytYTyIGHQvl35uWUCrgMbDBlTcGl9veJi1GbVdV99O8z9egr1fNcoZBMGl8YoTxRXBWWLpJnGTbyiBsm0et9mhkJ9i3zsqGGma5OV1jvvJ44Dvt8A62E0JQcTX6XmFu1tXnZ5R9pJydfHJDo6tlmdWwwGLE=,iv:QpjFzrO01KgW7uyfnvPMbyQVygBWFt8B5+v/KRUyu34=,tag:1xxDMlnTa/cJAXwk/BL6oA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
