apiVersion: v1
kind: Secret
metadata:
    name: protonvpn-secret
    namespace: media
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:lFMMilSlStv2YPjK9aBggUcNpQULx+cxsBul/ptzt1hbWtOn4Ipq6d7vrvU=,iv:Ox+30TWF78lUxXzHC3+yWdP+SfSZI+gM19u90sQTMPI=,tag:5w8VT30KL2mOm/iaxMCdDw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:73PnaWMVQhE3Kcs=,iv:J8Bo6qGI/IMFPxlv25OD313cmCUTKj1vGhRAP6S1tp4=,tag:tS9R2Kj6Gia/oaw2f1NWqg==,type:str]
    SERVER_HOSTNAMES: ""
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET0NMaGhIblB6dkhaZlJU
            ejMvTlhxRENJU0phU3ltTnJTSFRUZXJVOHpBCmZSdmVqR0hENzBkRStLeEhSWWFn
            T3RnbnQ4RDViTnBuWnE2TFF3RElPNGMKLS0tIGJRM0JON1ErVGZLQ21KM1E2VXQ3
            RXQ4MTdDUG9ySnhMUnFEVXRPRzlYbDgKKcEiQGBKQfxl7yhwEd9CEYAtz+N/zQ8T
            nKWpIWz42DlsgI9CsvpNBjXWylvaMkvTmbMuinjQdFnfTbQtUUDXbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T17:20:35Z"
    mac: ENC[AES256_GCM,data:iKKxowfJ0i2H31iMARED2ugbyRbFp0LLo/y8qTD7xFkjdhpUAi/aPwkBdgCZA8kJSsgJJfVbdTkAyb6jthp/L8j3lsPyRWREchXyLNskTCJ1GvCyIOS8wx9456LJATi/86Ko4hHwabt7njGCuYnKuUF9S/TRhcJ+Do9jC1Z1c3Y=,iv:i8ChoJvMfgAjOl4009swDsQvicFX3EAK6P6yazi04dE=,tag:SX7opZF4OQ3jDDsh+E7OVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
