apiVersion: v1
kind: Secret
metadata:
    name: soulseek-secret
    namespace: media
type: Opaque
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:WO2P5RH0YLEYJCx/Hw==,iv:jSLW7wHAu++zWev3kducQ6BJ7qbY/AVE7eV1t8Fvbxg=,tag:FExDMdxjzSaztlaSKU+tsA==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:87dlmZ8I9D4S1WRILRX00JPUOdc=,iv:o75TCcct0fdKLsmTtiqYQBEj1ELSLRUXFnzDbR1YNFg=,tag:SucZXvTV7zaxVzIWHrVMlw==,type:str]
    SLSKD_SLSK_API_KEY: ENC[AES256_GCM,data:vKWNq7gOUKndVrLAEUdrrC1DNvhm53d0mlIet5aI,iv:Z4HBoUqK0KV7pNeZq4oizr+zFYMKpivUu00UXoN6G5I=,tag:5eCl63/hpzUc2O9B2Oby9g==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMEZXWi8yNXpld1cwNTBL
            cWZwemlYK3BpV1dZRWVwZm1tYkZ2M0l0KzJjCjZTWklGV3h5MVZzTlNJTzE4a0hH
            ZjVVWkZzOXBKaFc1eWZPbGhDKzVHZWsKLS0tIHRmbjVwbUlyNm1Fd0JZeFVxUWFs
            a3BzOCs2ZDBYbnNTRWFDQzNhQmtiYncKWNThHHjQQl02eLHYCOn9gMOntqKGoJy8
            HTgqrg2VSQWBVl9TMLKVjK+3qs0w7JnK3Rznd++YCwH+6crtitqxZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T16:18:19Z"
    mac: ENC[AES256_GCM,data:1SGwggPrd1rFor52h/xV2yOLyebl+pWU/bWmGWDW6bjuCtm5nO1OT6J4cAkaUMDF5yZK48m8JzfTzDug/c5LkbiyWzFy0jW0rF8Af07cN7d9N4/poNq2ucleNmEjRNjtkXfur+Br+C5K0i/H5y+yAhD92hPshLslG5H0SzeldAg=,iv:9+6pJNqATFHAmXsyhXSSd7AKgihcFb7hgkGFL8juNmQ=,tag:/5GSWQRhV+zOis8sg3ZaQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
