apiVersion: v1
kind: Secret
metadata:
    name: claudebox-secrets
    namespace: claudebox
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:Kx6RX9yAIaCk4e53O1aFQNfBVTRixOygO1aoeDf/LL00jq3dHfP00CVOpArKvJVRHZlgT8SFQxiidGKeXeLLgUBHMCIF0vCwe62TCvhLsGntcQFiRsCkBBHMawd7,iv:2rq03fgxrWm9b8MYLXyoo5/9IpmRctTZau8YFz3lLWo=,tag:qSQURSM+pjfralXY/DYJUg==,type:str]
    GIT_AUTHOR_EMAIL: ENC[AES256_GCM,data:qAKkoQ5V9magRhktqy5m4Zqs8bVCdAR/Bw==,iv:KW+z43UXAw4/VcOuvNizM6iOPTVVqog38YvzShN5Rcc=,tag:RQlLo+EX+wQWsALYlfkBFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL0JUUzZWSkRodVBSQWlw
            eXBVdjRjVU1sU09iQkNLT01PbTFjbXp6SlFvCmsvb1lrNzZuKzVybmlIbFNNS1pL
            RExQdmNiSVhkdERvRXk2ZHpxaE9hZU0KLS0tIFBoS29WeGh5UU94OUdLaWRFbmll
            Tzh2RWt2M2FLR0hoLzRHRFZjNDRtQVEKeLXFDfYe9bdkobr5G60EOvqzc30onqe7
            72qVnKaIRpspbgS6g5O4F6kXFZ8IqlOiV4N2rq/VrQh7MjOKlFD1GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:03:32Z"
    mac: ENC[AES256_GCM,data:0zFcQR3BZz7H+1+FQnEGaTMtaJ84boG+r+y9le3xBPgr42eGtk/IKo8P/H0VDFWGqjEdXWIxKWkthumpC79iHWteTB7IfLnALQMI8HN7dEaJKdlOTQ9QJpcgujWt5uAMwvmwe382H1UwPvovNvTDUkJofvzawlzzH+BfQr9hMS0=,iv:31wHUS94tKUfr4T3R3HVhkTSJuP4uzRwMGmU14NVGfo=,tag:ATePUDefLyoxXweDMu0yfg==,type:str]
    version: 3.13.3
