apiVersion: v1
kind: Secret
metadata:
    name: claudebox-secrets
    namespace: claudebox
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:DgkqogBawDXX7n2EjVg6DP2RghxjgVP2u49IJTsZA7sguffSrDLQ6KvifzatkyQ1YdkE+kOEy4aIv9urpq8o034siK2oXEQgAPEmEkNr0lIk/Dy6ApU4sppPJo/1,iv:L2pxU7shftl3/tRwmwtzqKbx1IFJ+2KdWrY2IJkiH9E=,tag:tFVZUXi/+FBauv7cKBb6Ag==,type:str]
    GIT_AUTHOR_EMAIL: ENC[AES256_GCM,data:qAKkoQ5V9magRhktqy5m4Zqs8bVCdAR/Bw==,iv:KW+z43UXAw4/VcOuvNizM6iOPTVVqog38YvzShN5Rcc=,tag:RQlLo+EX+wQWsALYlfkBFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL0JUUzZWSkRodVBSQWlw
            eXBVdjRjVU1sU09iQkNLT01PbTFjbXp6SlFvCmsvb1lrNzZuKzVybmlIbFNNS1pL
            RExQdmNiSVhkdERvRXk2ZHpxaE9hZU0KLS0tIFBoS29WeGh5UU94OUdLaWRFbmll
            Tzh2RWt2M2FLR0hoLzRHRFZjNDRtQVEKeLXFDfYe9bdkobr5G60EOvqzc30onqe7
            72qVnKaIRpspbgS6g5O4F6kXFZ8IqlOiV4N2rq/VrQh7MjOKlFD1GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T14:38:13Z"
    mac: ENC[AES256_GCM,data:0Yz6ToQlIeODi0om63rMaOYcSI7VEY9qVlzrTcrp32/7JD+EJViWtIM1zQz6MtPXs8ziYncaTbfgACn4BidpEtxJGToNcoeGdXB/O7KR+YasFPIx+UCHXme0wfnNy8k7JURJANDWSoRkc1sBy/+W2chOBPtT3d6OUdPHYTPYQlw=,iv:iOoOlypxupx0R+AWDSvOcZrqpqyUDNVjB1jW1UaQTNg=,tag:vn/PJTOQGyV1yqPCQfR6SQ==,type:str]
    version: 3.13.3
