apiVersion: v1
kind: Secret
metadata:
    name: claudebox-secrets
    namespace: claudebox
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:Kx6RX9yAIaCk4e53O1aFQNfBVTRixOygO1aoeDf/LL00jq3dHfP00CVOpArKvJVRHZlgT8SFQxiidGKeXeLLgUBHMCIF0vCwe62TCvhLsGntcQFiRsCkBBHMawd7,iv:2rq03fgxrWm9b8MYLXyoo5/9IpmRctTZau8YFz3lLWo=,tag:qSQURSM+pjfralXY/DYJUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL0JUUzZWSkRodVBSQWlw
            eXBVdjRjVU1sU09iQkNLT01PbTFjbXp6SlFvCmsvb1lrNzZuKzVybmlIbFNNS1pL
            RExQdmNiSVhkdERvRXk2ZHpxaE9hZU0KLS0tIFBoS29WeGh5UU94OUdLaWRFbmll
            Tzh2RWt2M2FLR0hoLzRHRFZjNDRtQVEKeLXFDfYe9bdkobr5G60EOvqzc30onqe7
            72qVnKaIRpspbgS6g5O4F6kXFZ8IqlOiV4N2rq/VrQh7MjOKlFD1GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T15:48:27Z"
    mac: ENC[AES256_GCM,data:JLfMusADINpSReKR80NFfDERA99lxfCBCOAvGd9ThMBKFsJYkg2t2ahAQEmpnMR2WUnJDMsYOhi6OzvYZsfdEB+JJ1dB6LpieBYYomrI5JAgw5d0Dxc5DTNbCiVP2r054yr5qfpM3Q0Ny+rR9qGMr2o1gryILu6U+bH4zE5i4VI=,iv:rrzXWfZNH7tGm5CR3eZiCJrr+N8OB4YzqmkMDq+1htI=,tag:Hl1kPWYuKgJwNXETRO1TgA==,type:str]
    version: 3.13.3
