apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pxldi.de`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
      middlewares:
        - name: authentik-forward-auth
          namespace: traefik
