apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - rbac.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - ingressroute.yaml
components:
  - ../../infrastructure-config/networkpolicies/default-deny-ingress
  - ../../infrastructure-config/networkpolicies/allow-intra-namespace
  - ../../infrastructure-config/networkpolicies/allow-from-traefik
  - ../../infrastructure-config/networkpolicies/allow-from-monitoring
