apiVersion: v1
kind: Secret
metadata:
    name: homepage-widgets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:a2anR/Mt1yLJamWvgnZhVE+dtBGkQXI5tO/CHxA9Hv8=,iv:TsV1fk8ZCVcmgJd9TocwrQTArphsrwjuQ8AZ6qd9fAg=,tag:y+A3nr5p4gogkPTvceb4Tw==,type:str]
    HOMEPAGE_VAR_NAVIDROME_USER: ENC[AES256_GCM,data:dm5XgnxIuw==,iv:oMjJXjlc09cTiweEsduXnZo5PcTETlOz0OjcIfdCL6w=,tag:dfwEnbzeH9DmeF0ADfMJ9w==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:HIcj7WP9YWfqTuryGUmn4PuTHskFI74Ea1zLLpcv/+Y=,iv:fAkeiU6stnKNoYdhB0127NE5t3/rL6Lmxps88TGHU8Q=,tag:jDFHAjAZMG+8NneXUmxNdQ==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:pKY/MjhMEpU=,iv:xslCf+poVNkPrGol1UdKsKrIUsV60ZEsJ/CGm5F/Kuo=,tag:agR5S/7pa1NNSkXVR9RwPQ==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:ksxOyW9lPw56K587YGTvFiF0cduTPpy9m0Q+jTzK6A1Fa6U1rqy/rZRSIA==,iv:hpUTM3VrGdfBbF9edXPsOzuTnQ3xFr7/6zsi+q7Zw/0=,tag:NmqX7uPClJSiQ2xUf6bDNg==,type:str]
    HOMEPAGE_VAR_JELLYSEERR_KEY: ENC[AES256_GCM,data:lzDl4Z2Ow/XWC72NSsS+IA/hbRHUUZbl/EzLmazpjx1XItL3gxttlLjRPv8YKsgkodRINTHvFnfzfNmNwL+RFtd0t78=,iv:xhdhi+lAE2ZljzxZIeqrD8Caw0bdUSe8HKeo6gjt4jk=,tag:FGCH04qMGQJ/ZqjejcVeCg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:edon2cpXdpphRWZQLHuIbwGpv+3nsfytZSO+AZ4BxqI=,iv:VhlAMupsIr9ER6tWl8NJt7kAQo3i7Q+HRltek2169JY=,tag:G8M8VnSedsInMQ44duRdhA==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:cUa2LVsp5SGQK/Hif/HFXZymbdJkg9Gxbr9vo+vGFbg=,iv:O6eVL7ZX/Ww56KQE9JwZNIOjJlfy5Nc+75RW0gVBkVg=,tag:dg4UZ+TJccmzQ7Exdo3qmg==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:mUQTrE/gxLQAAmlpHmJ2/+sIUZH6zbFiv2kOq81W3+4=,iv:L+LwgoWC5w/DYgjoPSjnZSzo2H9iKjPg8AeKjBxkzVA=,tag:qxqiQ1kBdIZPGuVbcuBvIg==,type:str]
    HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:IwZaReGcrMRhMpGCdH6N0xU4qHBCPYDxJEktdna1/Jk=,iv:Vk4rjAPab96PchXrt3wlcqV5y6pBrNSNY5YDikxyb6Q=,tag:xdhXWuGNfl5EzOEgnQ2kkA==,type:str]
    HOMEPAGE_VAR_NEXTCLOUD_USER: ENC[AES256_GCM,data:+9g2mVWsaA==,iv:sk/AFtFU5idtUdJ8zjqLzRouYOm7enbxKNUe/5NA4/0=,tag:OIOkUf3E9aGC+nMgcTdcUg==,type:str]
    HOMEPAGE_VAR_NEXTCLOUD_PASS: ENC[AES256_GCM,data:DCf/MmnSzDmgLvN890zQOwf5uqHw/0XAhQJJPErn,iv:zk8p9gDbkxnq1jhrA3oFn+Dk9KhJ6r9XxKtbAx++Tns=,tag:PQM17Hc4xP8z1UE5UzU+lg==,type:str]
    HOMEPAGE_VAR_PAPERLESS_USER: ENC[AES256_GCM,data:s5EmVfs=,iv:tcg1ajLku7FO5wN5SICZLKCM5NEOILRexJzy4P+UaHk=,tag:1xif/IBfzFnhFJ13nnMMqQ==,type:str]
    HOMEPAGE_VAR_PAPERLESS_PASS: ENC[AES256_GCM,data:0a5cbCbT9zXZ78Stm+jreTec2LOTEekWEDgGAiLs,iv:3kOHMVH8vMcFtCvqDq4CbjWBoPtnuh1J/3NkQSr15iI=,tag:9V/OldSDqI8/aSmSlGZtog==,type:str]
    HOMEPAGE_VAR_TANDOOR_KEY: ENC[AES256_GCM,data:wSHWrZBEjR2WOYaUZSaq/80QbnLgbW0atmzwFPPIaWyccL8aKMQfbQ==,iv:C7U2nFnIp/HRmLEbRm6z1bRnzBoBMwCaok1todz3v4A=,tag:zd9HXvxfiuVEDq+ZnvIxeg==,type:str]
    HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:F/FcS8rQoZm1+bot8w+1fsyFGnT3ew1wW4ZWyYAvxDhFGMFwRbWeXx0sNfoIWuN/MGjdCr1K6knhjLAS,iv:HxllqEz81Vx6QBuWbwx2APgM6WBms8lSIhqRtzFcNEI=,tag:VyFq40GN+u6whW4T9GuFcw==,type:str]
    HOMEPAGE_VAR_GRIMMORY_USERNAME: ENC[AES256_GCM,data:2gt2BFoezA==,iv:9vO72/++z7OSArc+wSr12tAizN9e778aTBKH+maTswM=,tag:As2BPCPrZ/rJkOAkfiXTpg==,type:str]
    HOMEPAGE_VAR_GRIMMORY_PASSWORD: ENC[AES256_GCM,data:P4iBLaSxmVhEN2Cib9VFSDkBjCHn7qC+JgO7bKLt,iv:tfIGH3RQPEfh4lvKhsLGzE7yClLynyVHQBZ34UYDwFc=,tag:aK5RHY4djo7QzxcJN3wqww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eE1KVktGRDkvdDZUbFht
            dDNCUkp1bTYyU0hVWVY2NmFsVlJTK3ZFaVhJCkRKYXY3OXNlc1VnTnRrQ2ErZEZF
            K1l4STh0NWphWlVFdTRUYW9qck1CMmMKLS0tIFh4OWgxcjVhR1NJaU5oWlprL3RN
            SXgrb1hrcXVVNG9NVlB4VEZtZU5naEUK/CIIKKko9PlrrKy3YJ0fJh4MEuFtgMkE
            tyuBX5sPGqykkWy9mbf5wbUwSP6XhXhzsfbIwtaJ7E6BcQvvTO+1Ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T18:26:38Z"
    mac: ENC[AES256_GCM,data:dICHgSkSLccGANu4I/v4f8qvnV5q1mf+TWqLoBijTJLhk+eHlkOjDU6ytOCQyzat2fbgeenRNzbhI17tOIStkPsvVivE00OxYyXGpCnNOV/r+LIyIim8rK9wastzPnUCdpbI0TNq0LPQQ3tQTqiah3ezL73l+i2PvE1lINQTPio=,iv:4N9SFMSMn9vZn4dfv/2+sZKYMLZlvsVerZQ/DdGelu0=,tag:V/5GLh0nqce52/LwIy6Ovg==,type:str]
    version: 3.13.1
