apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pxldi-de-tls
  namespace: traefik
spec:
  secretName: pxldi-de-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "pxldi.de"
    - "*.pxldi.de"
