apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: crowdsec-bouncer
    namespace: traefik
stringData:
    key: ENC[AES256_GCM,data:Z4a99p6T4BO8XXdr1ZUV4nSXpQZGKjab8To0DV1bz0+bXB0cT9ehiA1Xao+OulI8Uex1+rjdmE6NC1VsLW4+Gw==,iv:17DXmHFUqWcBveUAqV/v2sOC2y+wF/ZhqtvNH+macLo=,tag:2DQg73KozbpHFZvMTwJjfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRXJIaXNJSXRWcU1MYVRP
            RmxIdVE1R1pIUGdzdjJKb2xUcTdzWHZuNnhvClVSR1FTbWZMbWxaMldMTXBEd3Bp
            UGJqc1R1bC9IS1BVRVZERTJmayt4M2MKLS0tIDk2RkMvT3hJRE1mZzhJbXhSb3hH
            U2Eyd3U0OGpKVTA0WnAxVWpDMjgrVWsKyWV0zmBxClwvh1xQx5tO5ni5trIDJQhf
            7mX+O7UQ4k91X+xTIm78YJCo3C2v5B7I8pIa6kIpxlBrRNVn635JkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T21:53:26Z"
    mac: ENC[AES256_GCM,data:nVK+uKugtSkaEHRQlbVXOason+fzyVjwK+oLNsegulw3v3mdPVeeM1HftY2qCxptyc9di3dZmbE5/jJ7ciNeV0JdsC8eAWh8A5AAW0YZa1uYMpHqjzOkOJMTsJKS3Mh5IaOeFkucv6FvoaVmJ2RCeVDj3HkwNGPO5DkMbHvwJXw=,iv:ridOjmFsZNzqRZa9d3oMyjhjprv3hBtOP5JZA+Yk8FU=,tag:P5n5OF1FeiFQVZhjQTj1aA==,type:str]
    version: 3.13.3
