apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - secret.yaml
  - helmrelease.yaml
  - dashboard-secret.yaml
  - certificate.yaml
  - prometheusrule.yaml
  - traefik-api.yaml
