apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:zk+hzo7X+163IbxqkNZbyDBTtqsIIfxSyFYUEsTytiR3ku+72e/QQQ==,iv:IdLxyV7+qJ/iuHFIHv+nGuvv7VyDPsHeRpKrHINKy/0=,tag:OBN+7p/zOWVjIxOU6ORYjA==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VjNXK2d4ekNkTFdHd1U1
            MW5yYTh1RVh4ZUVNMXRFZUlyVUNwSDUyd2kwCllWdUIxY05kQzZzY0ZCRXgzZFZl
            ajRlcEVDUWs4TzlaQnlVbi9oekxxU00KLS0tIDJFVDUrckViQjRaTzJpVHVIOHRz
            ZlVxRk5BWEc1ckwxNjJVVnZJa2swODgKJx5cf05sDo9wSqUHh7c6YLQnOrw/LXte
            xjn/EU0KQ9jV2qSpTgwSC6oOjgBMkRF6MMwPRVV1y2qOINXub+qPhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:00:33Z"
    mac: ENC[AES256_GCM,data:wHLKryNI1aw8gwHtQOq6uBw5LsDt5RTRzBpyFFDDnMzPYVQPJuCn9xQjtFA1vyChTDwqLB74EfSVNGGcVayg+uzAMNA1bbtnklO8A2p3yJ5lmvb4DbvlmcrbyW6LNb5FxPFrEjgM5oAUSJM16avHBQLl2Kg5o/ok5nmeKy/7FQ4=,iv:kFNF7o7bjkCLEDweRmrsRcjOBoszrhR9X+GYSrxx5vg=,tag:FFMRl12YufJN2Sze1huJ6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
