---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-sync-data-pvc
  namespace: obsidian-sync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 20Gi
