apiVersion: v1
kind: Secret
metadata:
    name: obsidian-sync-secret
    namespace: obsidian-sync
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:YzGktA/27Q==,iv:mGxsqJxsT69x2kpcZXXe22RV1rmgdIb3xtk5gS3zgD0=,tag:MWloHG5YDZ78aiNqQeet0Q==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:8Yf6Q6B6jOnBWic2uEr/MFnviOof/jJ5vKK/CBON,iv:2vo1XMbUF7OQxzcplpRxHc+BSlAchr3P53t5O8lvHJs=,tag:ulBxGSONrwZ9KxcERYF1TQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQWY4YVZLaTBzOFpOWWYv
            VnFrcXpQYys0aCtqN2xhTWVCa0JlTTNzU3pRClY0SXBJdUdaUUE2dVVlYnpvNHZM
            VkpaaS9EdThrZFBOUHZ4Ulp6MnR2UzgKLS0tIHBOTlRzdzdnNTZ0cTArNFNsckEw
            bXVtc3poMzZhUmswY1RGdkhZeC9Wb1kKrCcIitzrQ6lcI4sKYG+0AGCXbvXZmyF/
            w8GkkGnOcZOAGDJ0FasOa3SwOaBbzACqSx0izHv0Tyve5Qs82/gzjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T19:21:32Z"
    mac: ENC[AES256_GCM,data:r2NWac/Yy3/U9mNDh8l36UZx4KWNJcvfjF1PMwoa0Y69lDGuYH/9YsikaNcq6Xx8sv+LSzjx8hs/E6kenPPCefcH+5MWwFtwSkp6c5BrHKHOzJcxnDrkIMgVBbhOohmrqAHSYNnJgWR7QEzlbO1BA55AYro0T47L04RIvhY3leI=,iv:nnBAOa5xeRwK4p3vLOUBU1Crq0QKCLRgl6Z8VfvUFSU=,tag:jtyG+3/yFcNyUrOq8RI/jA==,type:str]
    version: 3.13.1
