apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-credentials
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:w77QZYL4WA==,iv:FUcP9EwbMEMKRJUOhqpKk8CqO0HDSj93DaMNV1f553w=,tag:7MF83WJ05GyA3x9N3VqQ1Q==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:Eqh+Pd/cyKf27hYGh4fFYOqTl1Xlw62lbLxEK8D2,iv:3LtE3aBl90AnsONlf0yHDLA97roJ9JWpIhWVXv9Khg0=,tag:liJWcm344cpMsw9Lm6q93A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:vvATetLRY4MJ,iv:qtXbMm64WScEHp3gV03GLkej23MVIPba4AVod19Abf8=,tag:+N/MSd/mE6p9s9HVIeSv2w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tXw+r/P7hjFFTqcZUwIcx2Yz3Qfp1Zu5/ma546Wv,iv:biGrsjXVe3YCxL0hyTHqoF/taVQeQzrJr7IjRk7wQ5U=,tag:xel6n03BP8/GSY2UKC/Ybg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:3jkIlNKHz+VenuxNDsgFag+ILANoK1cHUEKnQ0Kn,iv:yIFbQJL6dVl1e3a4AEXmg63Aw9/MkONSXz3MZFKNgPM=,tag:LpTBEm1cJ3fp5BpKsp5HRg==,type:str]
    redis-password: ENC[AES256_GCM,data:O8aSAzEHaJ0RP4O14xofNcBE0FrUVtcVDKVqhvhv,iv:j3oJryi00kHOMvkwUIgtpUDIfwGqWDR5RJ5miAbvxDY=,tag:W0Tj8ScF82GDgrTYcyW+og==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbW11NGdtYm0rOER6TkFJ
            K2VuUDdFTTFQSFBlU1J1NmxSVGlIMnhZa3pnClNnSUo3YXFrVEJ0U25ObEgzRTh1
            dG5PVjdjalloQktOMHd4UDFXSzBzdEUKLS0tIHBwUkV0dEE4VjBMWE0rQTdUV24r
            QWRBQVNqK0l0NEFQN000WUtRVVNxSE0Kr8hMrRo1eyH1m+s2w+Glhaw5bM7/mvdh
            S3DVXYb3Xfl1wCTLVqB2UX2gAFrJtnPZfQ+a/2h+l4Ao6H62BSbG8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T18:59:07Z"
    mac: ENC[AES256_GCM,data:3hGQpFGnB3FMkm+PVaGLCB7p1weUNfQ0ZvfrEvu+q8yNVaDoPuY6z1M6cyFgYV0vkBCHQb4uWfhepolNJnfy1/cJo2cpVZnnPW8C+7y8gM4/OUYmoggzLJS+G0bemCP7WS8pHFD/vX+kkhYa/YHShRqGdqZRyEuCmY+PHwgZHJ8=,iv:UTdZ7aVoXLXLx2RSo/c4D1TJ/mNK2+CswffioOO81c8=,tag:o7Wdgo0Ev/Q1ZwBOvb9atA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
