apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: karakeep
stringData:
    ping-key: ENC[AES256_GCM,data:cAx0h/3DKDW2rOa6XZ8krbQykfS6Wg==,iv:Hx2n2yI69KkeSpetqLeWHfHHfjphhulsz59YTM0M8ic=,tag:0BukyfWeUoBybAK3+3WXSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NmtNK1FLQS8zcml0T2dW
            NTd5aGJiU0NnRHJLc1p5WDM2Q2tCTnBMRldJCllaMVgxRUtpaXE2YUp3WGp2QW5X
            dmwybHoxMENOSk85VG9qWjJKSEhuZ2sKLS0tIDJ5ZnFDdG1pQ0ppY3hnNkhqMEZn
            SXdubDlHUFZrV1dvNnR1OVlmTW03aUkK2dot3nHm3i/6SkdRNxq8Y+vcLe/MY6sW
            A5eV4AIK8mKavCkYYxnHsLepDio7VHZjSBBpOdFX6YzlaL5lNlgqeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:04Z"
    mac: ENC[AES256_GCM,data:LQVqgnWW1Dhqpm3AkNNdNlJgNRbMfLxGiIrQ7Gvd+ZrCSh5I3P3q/HWQm/Ze179nHcK1ljAkEcRlAf/zABexPGZ+nm+8UKvGhN51a+ojHGiPbpURuIYnNAHk497Rc9Dvh0K2soIF4MHd8MWVtax8DhSSL/VJxUQ2x27TkkF2rbU=,iv:qxCGImsz2dLRu6T2jGWCILQpyHKcvUF4TK5+0Xaq5w0=,tag:VGkeEKzepG4cv/0ls4pX9w==,type:str]
    version: 3.13.2
