apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: karakeep
stringData:
    ping-key: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NmtNK1FLQS8zcml0T2dW
            NTd5aGJiU0NnRHJLc1p5WDM2Q2tCTnBMRldJCllaMVgxRUtpaXE2YUp3WGp2QW5X
            dmwybHoxMENOSk85VG9qWjJKSEhuZ2sKLS0tIDJ5ZnFDdG1pQ0ppY3hnNkhqMEZn
            SXdubDlHUFZrV1dvNnR1OVlmTW03aUkK2dot3nHm3i/6SkdRNxq8Y+vcLe/MY6sW
            A5eV4AIK8mKavCkYYxnHsLepDio7VHZjSBBpOdFX6YzlaL5lNlgqeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T22:00:58Z"
    mac: ENC[AES256_GCM,data:JhbLTqcMfs0IoRwqUp30n90i+ZZP2dz2Bymgyhz6uRlYBDM3NfLdPA36jxTBUSufTj87/IB1PqKCGiF96eyLEpNBzzNWm1MacG+degoWhZfSnYjUbH3RS2tvZt7rObn5MIVaF7DdavuaFASnc5PIJneuXuIRDeE4q2n6TTgFUNU=,iv:L9kQsDQVi/ervUryHE1Fiwa3C6rQkfKghijwnyorHnI=,tag:FNF4ObSVYBN9IoYeigD3PQ==,type:str]
    version: 3.13.2
