apiVersion: v1
kind: Secret
metadata:
    name: karakeep-credentials
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:gnucjuXR542jUyltfN2ZvQgr3vaH3J2gqEMyJ2Lfo66cLCTBuAdEEhE8ZkUpiyPi,iv:cZRlBAY9tkrp8It9AII80V9PYUTAyXbJ0aW6bJm93TA=,tag:P2kXaPA469oFFE9F59IwhA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:7AIa2vpeOtVvoHkgYhjYbuT+iOkb7NOQ8dydTeuloOxOrjLuHIqovIyOumVn6Ixn,iv:Bhkm3+s2Q4ra2gDWXkXUTqOJ4v+EePomQAWNqicCgbE=,tag:lFDEH7endhlnq24tEuuDEQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:gQ218QwlGhnhsghQVPgvIKMxIcFTO1RkGOmPWkE72F5yKwalOyUq6s8/sUmrmznTRZVFZNPWEAag7q04JMpK2A==,iv:mT05CJE0dEw3GvF2GNdfawk1xULClbJPoWKvfUu5YiQ=,tag:qEsjICJ6vpWkQe7TpAbb4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMzMxTzBYaDBxcng5Z1dp
            VWJtTEVOeEtLV3lVT2lkelEwZHdWc1FodXk0CnYxY3RpRHBTRFVSVUdwdkY3OFBw
            V2wrR0h0cmpkUVRIR3dMa3ovZTJPZjgKLS0tIElHUXl1TmRPQXRTdGtyeDlYVmdp
            cWRJWkdNOFU5SDR0ZGxITWVjNTE2SHcK1TKzbQAaLBiaS/9krTVABnmdin+hGMqw
            LHNP2KWSP2WHAhhP4RQDprMgxQf/vk2lLieyFtEdSQlCFfNJT4Wwow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T14:01:09Z"
    mac: ENC[AES256_GCM,data:ydSmRiG8CucsZK7C9XtCiGrUcqD8Kn7h3DiLvlISjQ0Hxi6DMFRehvv6DhDRkVOdSuHD7/cvyaFH1O4jXG+WfD1AkZ+ztOqj8IHYGjI7R0ljw4aSNIfDOcq9OlF9BCCtlX8xnw54IiYmnhcnkagBGWttmE4r2rfPjDQit/crU5c=,iv:k3kX6Ii412CH+D8Pydv2yP6/lj/aurabp4TQDxbJosU=,tag:WEOoOS/L3ZNQdUEDUHV8JQ==,type:str]
    version: 3.13.3
