apiVersion: v1
kind: Secret
metadata:
    name: gotify-bridge
    namespace: observability
type: Opaque
stringData:
    GOTIFY_TOKEN: ENC[AES256_GCM,data:pI74L8jg4n4Hj8ULuA+r,iv:Ea1qNZNFAsNRSeMmd4ekgYMpIREhxwyT8FC9NLHLanE=,tag:NjIG0TFVms+vugya6nqIUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN3BpU1R4ZFNKdVlyUDJB
            UkFIQzF6TUpydjYxT01zR3ZBZytPOFZkOFNzCnBFTWYrakE3K2Q1Qkl0WVU1dHdw
            UXdkTEcyNk9LbW8weGEyUmcwb3ZpRjQKLS0tIG1uSTJXdFN3RDJhWVB2UWJIbWRZ
            bTBXcUh2bk51Z3F5cjZ3TEtyenVxK28K7f0QlWmEZNw5DJdeVelpcLFKyo+w4ZzZ
            nuLn24G/ssNq8Uz9uTD5VigFHiCpOAazxrK7Nz2IkBAXnBklkTHVbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T09:14:05Z"
    mac: ENC[AES256_GCM,data:KWGp4tHm5YxydnsOcP/MDmIZk5HNrce0VvNc0T/aWvpQdp3cCF0HOl/XASVrQpgwbPu7Cog83vtIuAO56IqM48waX4V1J/5OTRlgVKVn/36BKUN35zBlRu6tJej83+tSeEuOkdW66slBe3VSl+tYBZFS8c03q1EtrNRsRxMjnMM=,iv:AXRA10RPQGXv+R+qHRVXbHVNuL4iTB0a+fvu+gaZO+U=,tag:0MxMimiXyh3Wuo8+UF+Eow==,type:str]
    version: 3.13.2
