apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: observability
stringData:
    watchdog-url: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WUd5b3c4UGtaV1hhMWYr
            NWw5NEp2SDI3VUFjRjlQMmRQcUIzckFZcEhJCitRT0Z6bzhqQVduU2FlMG1Iallm
            SDk4SjRWejBMdERvd3RxN0xEU3pvaGcKLS0tIEY0VkFwdFUySUtWM2hYMEoyQjU0
            dmR1eXFPSExiQnVkQ2hSbG12cng3R00KQHzW15BMRxSFNxdnL9FMtzB/cifsadUb
            gFQw9YBoMRZ4MTFpVrphXJOF+kT+fifSsmKT8qIzEQ5PwU2okYuAzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T22:00:58Z"
    mac: ENC[AES256_GCM,data:rJPE4DeLwmK3sWlv8djjCUJ5DUj18KF/Y4iSAs/vcy4ds+KkcQmnMtmF31JmaFoUhLn7rWb6Gcow3SejWgSQ5Bd+xqw9JfZooC93jEcYFioqRXX7GdXSjcx5poYOIKCOGfTG88Eta9MObxP8QZWwN6l88lbCAUxM+Erm384AYas=,iv:hS82efSh0+KZrDl8Hazzbr5RbkUnlMHgz3v/Te3GGWQ=,tag:W+B+c5YCHvQRFhbE98DRog==,type:str]
    version: 3.13.2
