apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: observability
stringData:
    watchdog-url: ENC[AES256_GCM,data:DUJWHsFlG1WOTgtDy4osjJ5ONBK9hOkzIwUDnIbUX/YGWHsRi6UM6H3gnEUSOx2H9cr0,iv:nCc1CQ5NiYA2yXg/2ZO6l3aYpsq6KX0G6rFQICsDBIU=,tag:4I+DCPfsNl4eSEBOMmhJaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WUd5b3c4UGtaV1hhMWYr
            NWw5NEp2SDI3VUFjRjlQMmRQcUIzckFZcEhJCitRT0Z6bzhqQVduU2FlMG1Iallm
            SDk4SjRWejBMdERvd3RxN0xEU3pvaGcKLS0tIEY0VkFwdFUySUtWM2hYMEoyQjU0
            dmR1eXFPSExiQnVkQ2hSbG12cng3R00KQHzW15BMRxSFNxdnL9FMtzB/cifsadUb
            gFQw9YBoMRZ4MTFpVrphXJOF+kT+fifSsmKT8qIzEQ5PwU2okYuAzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:04Z"
    mac: ENC[AES256_GCM,data:RsHL5x05OSSpDusl91h6Wzf7EJiGRHb3ISv+JB6vz/YIj4FkIV/S/mEzSS6c+66RDg1Euz7TIEuwx5T15EpedMpujveU6lectblsR6pzyaDUsmxOPQBlnszGHkIvvQZzPXHwLzL2g+/hmiVGTQKfrzBF6aytCxEKoZ/ldChVWwI=,iv:tRaF6nxQqThDdcWj1137OQLHuRNRDjFoJBojhgFxmCA=,tag:NxgeL+V9HrDpiMHXMT/4xw==,type:str]
    version: 3.13.2
