apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:pcqS8YA=,iv:MNtw2Nd5ayZ2nWeoYDbc0nfMyBVS812W4PLzHCK3WgE=,tag:4qzlraGnwZqX8Hq9hmCkWQ==,type:str]
    admin-password: ENC[AES256_GCM,data:84oGNxXRL9Uj4J/UzH4doYgLxCsYa/LocOtESQ==,iv:ghnAkX+1krFWnA+42QVu8vQICuz5UZ8XKNnl8UKoiaA=,tag:3Da7CmNz2YflVybwzv87gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ2dYV1NKRjNnbTVpd0Ny
            TG1MbkZFaFE4RXA3amlOZlFHNmljb0NFR3hNCkNWSUxudndmQzRCVFh6ZEZrVGd2
            M3E3U0FjQmloZytTUjl3N2NiQW1UU0UKLS0tIGxrVU1pcHU1d1BEUlBqUnVwL2Ri
            Q0VPKzJoNGRqTy9hL0cxVUFYVCtiaVUKsyLTalcUxuCUOInRXaIJ93avpzBHF110
            oaO6ZHUxz7DBVaWa3QClHyDHjufFoWnu72J0WYulnj7Kpv4Pio8ElQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T08:18:20Z"
    mac: ENC[AES256_GCM,data:G7/T7Di7IMKy1/j83uXoOwDmaWZvwCKxdfwE9odp6KMVHIfo4ACxjq8Up+zB0spRAsbFSclXOuMLtat1TABRi1nhLBOq8IHmP1V2WmC+do/iCKCAEDQ5TacGJKVJrq9DIHVsyeCbLgMU21PA9mSL8etIIq6Sa4Q9d1d+vi7wu18=,iv:DFY4LnPrPhWp+0+ntC11Q+S2MJBG9Yy91FhzzeSKXr4=,tag:BHZxyDsITf6d2RtfhFkfHg==,type:str]
    version: 3.13.2
