---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: overleaf
  namespace: overleaf
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`latex.pxldi.de`)
      priority: 10
      services:
        - name: main
          port: 80
