---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overleaf-data-pvc
  namespace: overleaf
  annotations:
    backup.velero.io/backup-volumes: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hdd1
  resources:
    requests:
      storage: 100Gi
