apiVersion: v1
kind: Secret
metadata:
    name: overleaf-credentials
    namespace: overleaf
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:Y7GPUEIAK8dBIy7KWiXbgpxolm00kkFbkfmNc02AWeisgJVR3YE1lBpMzIgGHb0x2oPRCS+cQeVVtAmZk3VPT9G3rhEZoUzIZq15nEt/gw==,iv:w2Qd9+Jl03OjHbp8zTm+7kg27uxqneokZOMB5DkOws0=,tag:HmPxqbuSKQRZbk20rfEVqg==,type:str]
    OVERLEAF_ADMIN_EMAIL: ENC[AES256_GCM,data:n5vrzmIGmsAMpUM=,iv:VJk0DJfdFacK9gDGYw6FIBDYkrj5UdsVSkss5GAfRc4=,tag:ECQHgh5A3D0Mm0TaIVhIwg==,type:str]
    OVERLEAF_ADMIN_PASSWORD: ENC[AES256_GCM,data:f7mdKaK/Xqt3s/g4gnyNvgFPBeRhD37DqjrKU17FSNowKSrJziUVqs+a9HNcHqeI7mepwY4/Ce6HuCoZ5A==,iv:F+/SUw0M6BvYXyRlD70RWi01X04kngScPUNRAeavNTs=,tag:gTXkC7LAH8SHBsZnosvwMQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:xGKrP6SJnJFbmzaTuEudKQfcpQ==,iv:n5zV5f9ZyeIW8knylh9C5H0vxPiJUnkEPQAU5SqwJcU=,tag:JjzKEeXga1agF4CDZTDHww==,type:str]
    OVERLEAF_INVITE_TOKEN_SECRET: ENC[AES256_GCM,data:ftA3OTZkOaOHj/8BrM2noEEnjEel/m06y9DxRbnNnYW/raDXxKFfB0/lRy4=,iv:7eGS3CumcOLoXUbTND47uShsRpUF01pIs/MtjXkXPZc=,tag:u8XC8YjLEldEpoXJ5f5DKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMVZrN1NVRXV5OWZVNUx3
            RmhCWkcyRFVDNWFKVEh6cjJDaWR4UUdkWXlBCnJ2a2NHOWJvQ2EwMHZLMUp2NDhX
            VnpEMWlVS1d5NG5CZ1ZkQ3Myd0lxK1UKLS0tIEpMWktDaU16NTdzRVJPMGM4VXNL
            YkpEaWZZOE16SzF2bzlqWUFaYTFsdmsK2xsv+607jrtGEDCmdPPglkrmtmpQt4Br
            rT+OcL8NxgA5HY2sRl1OvZQksm/12CSkOQIuEUP5bIuLQo9SWJLhSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T09:01:56Z"
    mac: ENC[AES256_GCM,data:Ox8NwN+YdL4KTrnDlFiNXScsAhArE8B2IuxVEO6uFwYG0hf5f1l7HJyQcYRo7b01N8XXUPssVBze3sOaZQUd7/gAaa94vrKT6VPx00/caWl4yjU6CdguUV/6eWwye6YJTpSmjyQ+dg2AM+WgEidtHeNxf/U51ej0qwfAgPHFhGk=,iv:uscdQV3hgSUAuh/fU4XcYGc+rP3Eun5HqCa8Ijdqbrs=,tag:/rXuFY+LxVgYb4pl3NssgA==,type:str]
    version: 3.11.0
