apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: firefly-importer
    namespace: firefly
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:aEvy+y0cUAaw+MIVg0pUJVd6Kc6IoxDG488K+IOMM1tPa65z0o+4OPvCQe64Rf3IFBI5ycJMZlNkMIX7wzI8z8T+qVB4/uqvaoLGjAfJAbyaFPR4cQ9BtWeoECFr1iep1AW6UOWO0qoKInqLRo8BOPJCNWz7iifRgEqhupWmf8TWiw+H6ZbS4rPQ51gzJwAvZz2ifeRmacqB2vEhtf/LN/A8KuYC93PqKaSlc8mCwnXK3pp35aMyJB9BAB8tQ8KdAQVa9scTxpFOkD3LMb5OpYr6pbfZIuOtqL7l21y5Av/0qDRx0ekQTDo6So5c8eutw1f8kBVnoJNOIzT49RE9kyA/1LKgImr4fEJmZFjIqXNuZo2Y0ZPJEMWDz8zcKZX6yqDScVkuPbgIYxFPpGgcSJY62i/vG31eLpYpCPNAaX/QTscHTKVLmzF02Q2QUVzUq9PrW05h5KgZwC8H2DE9Cw8U8Sq1TA93oELyaUaKUd83TY+VYvn7CH2+BidyUcrYb8SEwBjxBOexD3tp8FsF2Z85qgvi1dJd50i+MGtc73RqZrrLTH2lQvKgVetqGCjObf7Z8/HizGQlzT5hHV5S1UggqopVu4XLmuMecfrZkRmWbDWH3dwz/UBj+prPPN8s8zA+T5bUWaxPmKKPfEu99+Zg8jsEtSWe0yRM3u1+V9QNumtxscyguv5lnB3v3E93XL1DXq5+9KGBWKw77cJyqELjgdvW+KLpCFzEpGP+MMlfCMf637wZi66o8sGAazxNKRUV1etYxoZlgIEx5fLCLnzZZM06jqCj126IIWHczsIeJKysXJBINUrM8CIAm10Yp6fZlHlIDEOBd9jt4gsWYNayvryI1YOrnW/THLa9ol9qYCzeAP0pkH+gB1I2WZI7lGumBpwtpV2hxYA1rl1OqY3WQlKLfESHBPcIJdB+IBxjDeuCoWbv9Tc8GR5qGYw0ozEQZ+81PS1ZqgDZBXtcLrJ+kyGL1NaJDUokKz5u219xt0jXGlxxvDzCGcGdxkERniim1ZvtZmWpbfgcbvDUq2Ujzu+2vNxQnSpKxgeKHklo0G3zJT/hHh9H8pKYFdeAFdwNL/oR3caTMHabPKdqfRO5q1NfeuoDtsIqMfEdyeGsA2becR83zeH/3cTsdsP2VpFRwqk/qdS5vqV8RiQ2403UO85rFIQ0E6SPX0f7Pwm9dKZX6xmzoNF+E3cnu0kHqxl5u3GOCDiUuTqzPYr7/05mpHqgGEY2ulGQ9QB7/YzlX5OPa/83T8X9d1JIBwq73ZFig0ReNkLS0JQcRAzF0HL1ihKnKCmeQ7zrU81RulA+pnLMK2/zWs0BbabZCrh9pPWuP/bQp/MZ2gryUkm1lWA=,iv:h9QoeKHMPo6EvX5a88f/GyZU9ksaYAWcf/l5dhhmhrw=,tag:PuAGIOIlGAaPlrOJCEE1hg==,type:str]
    ENABLE_BANKING_APP_ID: ENC[AES256_GCM,data:I6dTWSyYVok=,iv:OcudOhc7D/lbUhoAycdAiNd1Qb4vWvt284AOqC7soqE=,tag:/ZMR9283Ne1vMHEHfCOWYA==,type:str]
    ENABLE_BANKING_PRIVATE_KEY: ENC[AES256_GCM,data:lQBbroReeEk=,iv:KAue0iu0B0U/lNx9hqftw9sYoc69kofC7gUdnlI+xbY=,tag:R0LUrvMpDNRP9kUEOeuwAA==,type:str]
    AUTO_IMPORT_SECRET: ENC[AES256_GCM,data:amya3VnBWIQvULzWWusyH11QfIT/A3o43BZ+sOpmXfg=,iv:xjhVooV7ZKMBhMgAvXnfU145Oczk1MXpKQIcD7GS6i4=,tag:2DgBoLmCapm6PpPkkrFLAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRHJ0TlJ6bXh5d2xocmo0
            RFlHdlQwMjJCclQxVkdhR2VZbUJPa1hxbTNRClJuSExRd1BiN3BMZTM5eGU0bTZ0
            VkhLMGlsK0E0bU5DUmVQazBsMzFVR0EKLS0tIDdsbE0vK2lWSmZqa0UvWFhQekdx
            bTZFaWlhck5HbUh4dkJuTzB1K1d4UFkKpFFQU459E6QCTO81qPzDyxLaEs+uDTuq
            ZPp1+CJnL1TrEtEFGUs5arsonBi3tSf+J/MGCBIa8oFBTyt6Qpe1tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T09:12:38Z"
    mac: ENC[AES256_GCM,data:OnLAI0LnG1nvYTOtwpvByqZ1QcaI4xBeGGqOx16SCLNev0i5rHO0Wd27s0kMvhCQoKSKz7Vw9ZgD7HK/iVlclWBQvZs38QEGGVpfTMvseW817bWKRLEUAkhlYwjfhdS/mGjNCitE6pw3T7kQ42ua/noxwAqRc3mKVje04JbdVoI=,iv:bKXpDXYgxedr5g5FtZCUMMcmUAEiqX3en3agFsI+lD4=,tag:v2YqIjtn5mT7BcHIy/aRIQ==,type:str]
    version: 3.13.3
