apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: firefly-app
    namespace: firefly
stringData:
    APP_KEY: ENC[AES256_GCM,data:zF8qdWGqJiBfWeG7xbNwlSs+1FEzhCJh60d8yt4dJgs=,iv:lB+Hn1dGoRiT1iNzkzAaBh8v879zpYgBr8zsabxRVgY=,tag:jnCrwRsD1lYWnarphr2glQ==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:9SifuVBGq4PkMzLW9YNhT3Vsca5ijR4r7N/6ACUh7I0=,iv:u0Z1e8s5xOJIm+7chkDgkA2+XOTwe7H3IMjK6dRG1TY=,tag:6b8BIOnepF/YuMxN1MAvGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOHFMeXZrWXBLUEZpcG1S
            WTBrSUlzWklSWHl6YXZxcURqajZFYk03ZlQ0CjEwS0phb3dZWk1hemJkSysyczk3
            QzJ4WTdvdWp1bWE1ajRhUzNSdnpucm8KLS0tIFR6K2d5R3Vabm90OHhqajQrSDJv
            dThqcisxd0x1Lzh5aUtOd3ZDc0hnL0UKUggcTX4Bbr0dK40JzPnO9o3B9wlCMX4i
            YbXacuVe+tdDdDyLv+6he7tzmPnkGtVnD5vpYBo0Xgtw8UaOdYeZXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T08:53:16Z"
    mac: ENC[AES256_GCM,data:huuoXv/EhOvPR6MzieEOKArE0i9C12uKmuvfdT8Bw4zRMi8KmjBm90WdW3RVJORuBK3/kHouXPPRie+Ww1+USgaDdgIrwMbsu1MqHuQ4BJkxr3OtpQbPJDGbw0JTjH6aMPtO8jQpmPeMcNO7Kauo6l3l3ctUM3hHZck323a6ZPY=,iv:6vpfBQwikdS95Ds7O1rFw9P6GJKcrLeGI/zE1dO8FuQ=,tag:2mGvLoINM8giXtSLns6WXw==,type:str]
    version: 3.13.3
