apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-immich
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/databases/immich
  prune: true
  timeout: 15m
  dependsOn:
    - name: infrastructure
    - name: infrastructure-config
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: immich-postgresql
      namespace: immich
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      current: has(status.conditions) && status.conditions.exists(c, c.type == 'Ready' && c.status == 'True')
