apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cnpg-b2-credentials
    namespace: firefly
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/cX/SRolsjj0TSvEr6Gm+nT+bkqQRnfy2A==,iv:SVkyTztvWGpEoyCgHvZ/cCgHMYktUuosDwbbCsFCkXg=,tag:N6qKavwoK2bjT1rhHWQtNg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:zaBco+nXZmnPrNU013FAbmUL1rHTs0VCBel9KlNZ7w==,iv:+d40k98bxtp/VoMpPUBxKdqwPIIfqib31LZbQlZ5GZs=,tag:qCuudekfhFHEOHuX15wnIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeXVnZEJselRZWDdndlFH
            YmJqdzRDWlJlLzNXamVnZno1c2lBY0YyRmpzCkhpdW8yOVlpQTdENW1OYUFKaXB4
            UXBIeEJVdDAyVEttVlNKMlFUaVdVQlUKLS0tIGV4OVNYQ0pOdjNzdHRTcXd6alI3
            Tnd5R2FNT2RGN3RwemJRUjlVdTBMK0EKm3f1vR+vVs/KlSdPXK8JWhkpJMc6qKJ3
            PISss9Fcaa0tRGsdsy2mjmiCieZybBO/eQiYjZeJQ6+jEYX4FlVxrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T08:53:16Z"
    mac: ENC[AES256_GCM,data:iS6kDvgK7OVwgDwm0G6pX0tpbAz3MYLqL3J1Qry+SnPd2rC1v918oPL8RmeA7+NmfMszmewCj1SKvRWW8hLqY/wddyr7Ruz6O7q8UbU1SL138jvUt599thfaygdUkAVtvkY2ny3mn3PPKOwEcZrD9ULI0ACVD0yFO9I/lZFYmLk=,iv:fjgUd5Sc5V6jF4ZMl34Ne3v9IlgqhLtmyo62IDXO4Hs=,tag:lcBU8AVkHXZG7UWxGkFa2Q==,type:str]
    version: 3.13.3
