---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: firefly-db-backup
  namespace: firefly
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://rechenzentrum-cnpg/firefly/firefly-db
    endpointURL: https://s3.eu-central-003.backblazeb2.com
    s3Credentials:
      accessKeyId:
        name: cnpg-b2-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-b2-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
  instanceSidecarConfiguration:
    resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
