apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: firefly-db-credentials
    namespace: firefly
stringData:
    username: ENC[AES256_GCM,data:0PMZqCjW7w==,iv:SuTVYfA3aJIf5p786ZzJJLfprWetjLhosmNLbsGLgVo=,tag:eDION3CyQL0Ya28ipt9ELw==,type:str]
    password: ENC[AES256_GCM,data:l3DzHxg270EpytXGoUbk7yiArIvbkXjyyFgyYd5BdbkiINNFVoXQqqdxYA==,iv:mx0YXzV6M/WAiME3AP29p5/Sf8s+NVFhf+OkteSgcwI=,tag:lPC+SQqEgCFyZiXvJZVbFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MHVnYjFWaVpPS0ViNjNW
            WFE0aVpxMVZza2JzSG81L0dtSlpEWU54WURFCkV2ZGZ0N1pwL083V201SDM1WERh
            VHpmRjd1WU5RaHBvekRIS3c5NmFSL0UKLS0tIE50TGRPdkRRenVWUDlHSHJLNk0x
            L3BndC9ReEswVlBYYjJOSXY4Q2Y0dGcKO2q3iZv2z8T8nQ9JHRAkx5gYy44phMQM
            bxWCzqLXCRhDHMGDbgACBa+B24Uq2woMKohGzYMEYGVg8b5Nb/1eug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T08:53:16Z"
    mac: ENC[AES256_GCM,data:xsGVZkLTj7gXQvD9WgnGvzYgzeTVxbg58i5hcJggSP8WYjL13h5fMPrNgVSaE1r6YguJX3ZkLDS46kts3JvP6Fxta062tPGUp2t7ypgyqddgPx3zUm4/uLRpRizZUJmj2a2+XnNVvFBtvdJyGrjYLo3jrzNS9Pv5n7o0YQemXgI=,iv:1zFhK30zgMrkNvhO3+38+NyoytpJZb5D923ICSxUOm4=,tag:inNqDoybeW5/PkN+nYFxjQ==,type:str]
    version: 3.13.3
