apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: selected-deployments
      spec:
        template:
          spec:
            automountServiceAccountToken: false
            securityContext:
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
