apiVersion: v1
kind: Secret
metadata:
    name: glance-github-token
    namespace: glance
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:k9Kdz7voBwRTKqlZMrL14iTrnd48PVzfAceIPj8AfzNoTuYGWntu4w==,iv:7yKjp7JXCU68ZSCGHm3soQDkDT0o+gTuLFnOSu+VcII=,tag:fLe8Uy119fE5SjeIWZH7rA==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNTV4Z0VHYnJuME44Q1Qx
            Qk1kYUUvdjkyWTE5QW4vbUJMaHRXTFVIeTNBCmZEa1RmUHVSZmp1MThuVGNZWU9q
            SXk2TDNCV3hmQ1ROWVNJU1FkbE91UE0KLS0tIG83TXorT1ErdFBvQTQ0N0RMWmYv
            S0hrcGFGcXRCREJjRjdCRm04WDdWcXcKqe0iGQKmGNe/SLpA9rjqiEkQF6MGNfgD
            E2/sjuTIrjDE2TUvYxh/wHkrhYulXbOCeM2e07l0gVDhzak3NbZYOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T22:21:46Z"
    mac: ENC[AES256_GCM,data:UzSL3G35VKnUZItzodjCl2E5IRohaJNUfJwZf8pJl+ZhpAn4Gn4eD/z/ZY2CmZoLSvBnYo2NqT9ylfn0L6V9pXaz/AodputhcIto1uOJGLx9gicxL+bCSlVdXZW5HFNo4zgto6TKRMyDBWw7nbLwz0roxKhVuKlYpCkStqWG3s4=,iv:11PuWY/H1codeh6YZFHbMlcgm0nTLDNCuIWQTpcNHPg=,tag:Fu9QFolnn6bH3KRbGqW8ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
