apiVersion: v1
kind: Secret
metadata:
    name: navidrome-secret
    namespace: media
type: Opaque
stringData:
    LASTFM_APIKEY: ENC[AES256_GCM,data:P255zCIOSAxsBtI0FmwJ8+8V50wF+udjwZG1lnvnKUs=,iv:wVINjtVIvS7/brL0OG9q6143m3Rvq66Kc/j30zdVHHc=,tag:K+szu7H8z3fu6aFwxZvZtA==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:9sbxkaPvGE7W+PU+/C1KXp2SYIZ109YslfTq/xImGMs=,iv:jtVojGYTqlYpPsTgxhVFZir5brZdfPr5D79bk94USIk=,tag:zsoOrExFELFUw2QvtyeJfA==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV3BkQzR5MTRXSlpGL0Y3
            R3Y2MHV6b3FqTXdITlJGcCtqWW1ucUROaUVNCjRlOTJuVUh4bC84aTd6N05PQnZu
            MVk2Nlllby9aK1hNMjZMMm1kbWI2Qm8KLS0tIEJnRmd4bmJRNG1DSm5leVpHUUcy
            bVRLaDMvY3liTkZmRG4xM29uTis0Q3cK03nl+y3tRrnv9Ns6kIXF2iKICk3HUirM
            vnCdquOXy2RQAURp6bbGaMCqCz9g1VG0SYwHWFiFi3IDUzRol33aAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T23:11:37Z"
    mac: ENC[AES256_GCM,data:pWXp97v+HSXvHUXw5Q6jkK0ve1R3GI/I1bjQYBDUgvzFTQNNHsDdGp6FRhxQ1zmTal+5pIiHaiNhgIWMSxiIyBp8lKIyz+Ub7JG0ccG65NOj7SSXuN0XAQhwx6sKjaMEch2twoqwR3uLM29CLwAFIAsO62juBJjvhg7ePLsMDp4=,iv:6JAkRV1cdRlSBQBuDukRC3Y6TqqICqPzZtmMb9cWrdY=,tag:fHjNvdYA5mpv3OD+pnlntg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
