---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account-hardening
  - monitoring
  - searxng
  - tandoor
  - media
  - slskd
  - nextcloud
  - jdownloader
  - immich
  - gotify
  - n8n
  - overleaf
  - adventurelog
  - paperless-ngx
  - grimmory
  - glance
  - ollama
  - whisper-cpp
  - fredy
  - sure
  - sparky-fitness
  - gethomepage
  - ryot
  - home-assistant
  - obsidian
  - palworld
  - claudebox
  - minecraft
  - actions-runner
  - excalidraw
  - karakeep
