---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account-hardening
  - monitoring
  - searxng
  - tandoor
  - media
  - slskd
  - nextcloud
  - jdownloader
  - immich
  - gotify
  - adventurelog
  - paperless-ngx
  - grimmory
  - ollama
  - whisper-cpp
  - fredy
  - home-assistant
  - obsidian
  - palworld
  - claudebox
  - minecraft
  - actions-runner
  - excalidraw
  - karakeep
  - opengym
  - chatops
  - wealthfolio
