apiVersion: v1
kind: Secret
metadata:
    name: authentik-credentials
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:+5Xk8nvBjJud33s5ofAR4ZkBLkbqa7TRJamt61pQ,iv:rPPUIgrlzBBQ+2Sk8AhSWxKAGvfjndgrFkfxVElxdpA=,tag:06PZpVpmlWLaVd4AOncbaA==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:7bqBQrrVpizPY5S1AK48nVXBDDz8ofdRI3fOSpIwTa6U2jwKDQIT2imgfJfv9AMkrDiK3tf2AePgCx9HIo2ED87T30mEBOL0i6lGKi5WKOw=,iv:AfYZ3+IZDrAj9Rigb8Y6+s99vcFqYuT5RMC9y9bWehc=,tag:G+R8/m5Qcln/LKHoSKVChQ==,type:str]
    password: ENC[AES256_GCM,data:o2t+cd21r4UQQjIzTrb6V5fD6UGMQEVeiAjRlIXd,iv:DiAMQsFNJ934b5FEnXsLeckcTii1OL1RgSk9cnLDo3s=,tag:VRPej2u9pam4zzm+xSNrPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQmYrMDRncG5mbzExUHZB
            UzNJVGRYM3BSSm9Wbndrd2txN2RvU3E0ZjI0ClBod1dlUkdMUzdsMGR1c1hYWGtG
            TXo3YTlmeHZTSUw4eFBKd0xxRC9tdzAKLS0tIHhINXp1Tm13anhoSHJielp3ZEtw
            dmJqVzBaTnQxWW9IdTJCSWQzQnNIR1EKvmlhrpStmsVHsUBdsZQIJEb2vHvnzkvY
            22mLjh79fR/Y5kVbHE4/4wiWiF0zLGz2Mx7PKvfQ5DNploSdgH71aQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T22:52:51Z"
    mac: ENC[AES256_GCM,data:ckoKyFSygyR8K58igEghn6hqdtOtW1nDs3rwUYLnA89DlrzPz+0/hAOWN0GABNoRCZUV3IN80RrzVCH0i9lGk36Dc210dj1lbsQko67ZiZ+HUaZUZefLF/HT1zL6P1U1va1z9QYR901VQa1OqBzjcfBaUr7HYkvBl5wA4z+s5cU=,iv:i9TeVix1xA0JaKNlR0Jp3u9HxQt1m3bL/VPRfbZeZ0o=,tag:aS/qQyQyGdXHAQu0xxHyAQ==,type:str]
    version: 3.13.3
