apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflare-ddns
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:UZYNg5wTO+ozDTdTOTrQIy+16j/c50Emkuan7MP3EdCovMef+1Op9w==,iv:7elQfmUIK0LopJxAR0R55pcdBTTKaJoqRv8Jj1L2450=,tag:znIi5L2Wwl0uCO0zNfNr/A==,type:str]
    CLOUDFLARE_SUBDOMAIN: ENC[AES256_GCM,data:a0SL8faSfhCf1Q==,iv:5MmRN3/JO1QqM+mfk7tCARpr9PyY6lu/X4Ahmvtvaj4=,tag:zlNeRLy0V2IIPp/qk2lVNA==,type:str]
    CLOUDFLARE_PROXIED: ENC[AES256_GCM,data:8hlVkX4=,iv:e87H5OyUE3fUuucb4kjJeqrDAOP1diWlAaJJAS+NkiY=,tag:Y/A7gaCEP9Q67Fu7jAyeRA==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a25VOGZIV09qOEthcGxM
            eDhBaG10K0VOT1k1a2pjb0E1UWN1Vzc5VHdVCm1Vd2Fic2IzZ2tDdlF6RVh0YXhW
            ZzlYMS9sZDdTNktUbWNnUHVJSjNVM1EKLS0tIHZoOE9mMTVyQjRYS3hON0FIWXNi
            TGE5WUVDQXo5VFloN0kzZWtvR1lWMVkKFaetQscvPU6cqvSaa19m8qNztlBfTVzr
            BbwF65EKRrqy6oiT5F0zsCenMaLYnDyxi80AWlgVK9QpprUiNWa9Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T18:45:34Z"
    mac: ENC[AES256_GCM,data:adz7tkQ78cOh+2HMRD1JARCWsvmNlNEUU+Da4KEYRPXrtyOpNVPfgL5IWCTt9/jnpka6hLnfnDJHxM1M5hwaTdK11j2s1ZMd81OYTaiaD4oDBwkibTxGqfvZF0otgxVz4NqPdQ1jsAdCBAEkCLXykyYfrVwKbZNuUl1D0ZZxCE0=,iv:Z1rCCOaJnl2wWNmiCAulMs49RhZ05VvQSxYeDczO/eo=,tag:rAgUxHAypxksL7Pd4ngg0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
