---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data-pvc
  namespace: gotify
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 5Gi
