apiVersion: v1
kind: Secret
metadata:
    name: multica-daemon-secrets
    namespace: multica-daemon
type: Opaque
stringData:
    MULTICA_TOKEN: ENC[AES256_GCM,data:DFKM586u178MsZzJ57v3pqiWMqfojV2hjSehUc/zYi985C2KnMI2nbYYJ2I=,iv:ph16zZ441zhckGYsDnlkjppGqyshgmI9QbZfIKRsXSY=,tag:Fuqq8e0PtlyoxHWPWlIzkg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:IPe/lCFoRnzIVgQLBLbfSnxRhHwETtmhapvhHnQ2OrVicDi2C6P01a44C2rKDhxPhAU0S140lqMRtvbpqJNAywE/bC02O5hN4l9mUdBGIzEV0c0HCCrKrjfXMEch,iv:oZYZMYivYpRhrlv77xd7CrLC1hshNfhbe2xGX8KBkkY=,tag:G6Y6yRc3DxWIwLWns0Ai3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NnNUQVF0dzFvYzNFK1dt
            c3dtdS9hR0hsV3ZPbHFEM2c1azltelM2NUd3Ckl5UTZ3ZGlPS1gweTUySDRCMTIx
            MDdQbDB3bWQ4Tm9EZDlkVGpoN0k3RTQKLS0tIElHNjZRTzFnbEEyTjF3ZlQ3Mk5E
            dXFBeTV4RU95Yzdra25YMUdIdURISFEKMUf6IMKhbmb++ePVfy2OjDwQWK4mhklW
            5w6Ie6tdQC+w/G3mMDHgXF+L1ORF4FUpsBGfXjfiisp1oSQjVaJSLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T21:52:34Z"
    mac: ENC[AES256_GCM,data:5tKwAFIWNKD1bRM/4Au9pEHQFxk3h8pamC32W2uK7q6ce/GXzbICeBAfpS5dK2ULiirSA2ORyUQqKjrWMlH+oHB05zqSkuV+H+FpV6ho1C0kxsrEzDWudGyOlmly4JR2cka/tDZAEbf9IlsMKdOJlfQvT5gVvzlgaXx5owQlJe8=,iv:gml8axx/SNFbUVN1DFSiOYGjboM9SgkCmIDuKEcx+pM=,tag:IcfzcfjTHTcgQ4FDBcJP1A==,type:str]
    version: 3.13.3
