apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-cpp-models
  namespace: whisper-cpp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 5Gi
