apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wardrowbe
resources:
  - postgres.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - cnpg-b2-credentials-secret.yaml
  - networkpolicy.yaml
  - secret.yaml
