apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cnpg-b2-credentials
    namespace: immich
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:eqyzH+qavMSxnEa3M/o8aNMsL02/xf3f1g==,iv:fBbnkpNOviDvzLw3yrixlFomW3tMkgmdVeeFfHvfHoE=,tag:MU3xp/sKVIsjLWODA0s/5Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:ra+8jDN4KE2ajPs7o0RSHXxj7Jzbr9Jsd2+h/NOFtg==,iv:gGz3mePdaB2hHCpHEexAkbiZHNJZ/tW0xP5hqZS68/g=,tag:K49fnraDbBLqXJ+RhUI66w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbEFHdFBhMU9BeEVsSEc5
            b21CYXdJRzFVRGVsMXV5dE83T2tnbkFSZERJClpyV0dHLzF6Mm5KTVBQMUFSUS9t
            c1FQa05GblpQVUxFVWk0cGpTNWRiMDAKLS0tIFdVNGtuY041TnFyUFRvdjVNREh2
            R3Zzc0NmbXB0Z01uU1hFQlBSMFZSNGsK/z3Ih78/8F0TjidA/81SonTSKROdf5T+
            DsS9XIESfuRjMWcXKfNUuczH0BF6mHd8wxovN7qFVlcU1CS5XEfdUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:38:29Z"
    mac: ENC[AES256_GCM,data:ywW4TTMczAyyXkfuyBJrb2yw1EPvVxzCHKEFeJ05mhd5Uxv0bDHHGwlO9YCC5kIUTvKUaduDmC6VTpr67Rg01PgALI1PajLdb3tvjYNSJL9V9a+iSwLdx76+z6Uouoihtmbcow0f2RI9e9Qsisp5MbLOLE4eHUAWTToyMstc/Mw=,iv:uW4hD5GJ6StgW8E3We6pF6iQ+Dgyty/Ei365ObHdBKw=,tag:J4gjpFo7JzAog902anSMmw==,type:str]
    version: 3.13.3
