apiVersion: v1
kind: Secret
metadata:
    name: adventurelog-secret
    namespace: adventurelog
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:O5I1Ra2bXV/X6YzQUHxYdb+a/IDENABzGDbHTBMj,iv:xDwvfXHZXkEpaH1pwqegfjaXPwVHmDv5ag1g0ncc6Ng=,tag:QpPKMUkFOK7oQc2KFn+gUw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:dbBJv3TaebgXV12d1vS3gx/ZaciXMqDqFxdlsldm,iv:an7GkV414igrAuCVWbARHDxhapy3jKB0UNhN6Q8GWRE=,tag:T1QTkRgVo8IDCUiiCnkYYw==,type:str]
    DJANGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:wXfgRqKAx8rzfp8ekLsmhNG6qY2aS//Fau0+e1GC,iv:w8jVr1GktGbUtUo4tgtpYQodYSVO+yQJtwm31pg3UiU=,tag:FLHCFQ2+TZmjkUDP/Adt0w==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSVJ4MkFVRDJadzYwYlA3
            cVJXUzIwNFQ0THJOQmxGWS9qSm5oZ3VERXpvCmFwTUtmWGJBU0xUYkNBODZ4SnM3
            Z0JYQUZ5RzV1Zkp5MWZoOFBOSWhTMkUKLS0tIFBZYlp6Rk1vOElmZ0JraE9kSjZD
            aERLQmwxVk9INXZUcUl2WDFrc0hLdzgK5qTK6cu4o+8qtArqg3+2V5bJ4NFQZZ81
            DmN7BztvMpKYWhIIQuUW2jPHaCNKYAsJ1ltU/OiR27a3IGC2Bz1s6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T12:11:47Z"
    mac: ENC[AES256_GCM,data:P/8WBfitSMcM8W1dzSAhS6WQa5M0vnqR8RvEfyOUNp7D5n1Pfi81Y46v+izEYd0CnrZqohxoD1HQXRs0l1xtrCWT1iyAuaUHHL31+LBOh1jQ2ul4P4qxPgQPY30xOi76ueWHPEa+Z7HFU3agx883t2YAri4mnpI8fi7rA6rpwKA=,iv:TMk94c5u8U3BiHp3rkGFB6cPUlXnfj0ng89EgcFonY8=,tag:CK7t1zO2Jr81kiR7YLH0BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
