apiVersion: v1
kind: Secret
metadata:
    name: adventurelog-secret
    namespace: adventurelog
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:O5I1Ra2bXV/X6YzQUHxYdb+a/IDENABzGDbHTBMj,iv:xDwvfXHZXkEpaH1pwqegfjaXPwVHmDv5ag1g0ncc6Ng=,tag:QpPKMUkFOK7oQc2KFn+gUw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:dbBJv3TaebgXV12d1vS3gx/ZaciXMqDqFxdlsldm,iv:an7GkV414igrAuCVWbARHDxhapy3jKB0UNhN6Q8GWRE=,tag:T1QTkRgVo8IDCUiiCnkYYw==,type:str]
    DJANGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:wXfgRqKAx8rzfp8ekLsmhNG6qY2aS//Fau0+e1GC,iv:w8jVr1GktGbUtUo4tgtpYQodYSVO+yQJtwm31pg3UiU=,tag:FLHCFQ2+TZmjkUDP/Adt0w==,type:str]
    DJANGO_ADMIN_EMAIL: ENC[AES256_GCM,data:uxsc8v+nwQyvCmYc9pc=,iv:N4dNtGioDJHNp9t2DONnndojCYoBqL6U5f2QJRxeIbw=,tag:GtjmENffEC9hRqerf95Y0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSVJ4MkFVRDJadzYwYlA3
            cVJXUzIwNFQ0THJOQmxGWS9qSm5oZ3VERXpvCmFwTUtmWGJBU0xUYkNBODZ4SnM3
            Z0JYQUZ5RzV1Zkp5MWZoOFBOSWhTMkUKLS0tIFBZYlp6Rk1vOElmZ0JraE9kSjZD
            aERLQmwxVk9INXZUcUl2WDFrc0hLdzgK5qTK6cu4o+8qtArqg3+2V5bJ4NFQZZ81
            DmN7BztvMpKYWhIIQuUW2jPHaCNKYAsJ1ltU/OiR27a3IGC2Bz1s6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:03:36Z"
    mac: ENC[AES256_GCM,data:hCpw1yUWP9nDzJXvWmxrGO8hRih4I8DlQxjcsbjVukQV5PwJJxajAAb+9ilGnM1QaStZxR0shlIu/7QVoku3GOEx+fZKcP6s0M02kmhtLot+w2EdS25K5kHrrLuht9uYzeCd/d6IjOvMxJyQEVnqABgmPJveQ/wXF8IH7o91VFQ=,iv:y0xxXy/tYgxa1WG38M56xOBQGpZ20X4b/5/PYMDgUYw=,tag:4Qf6vc8zFpxgIWJRMjpkQA==,type:str]
    version: 3.11.0
