apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: snacky
stringData:
    ping-key: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNzRMUGp4UHU1UGJUUDFh
            Q1h2dzRkTUFWMGJTWkZlZkxDZUZkUVZIZEVNCjJKVUNWeUppUlM1ZXFucGxnN3pz
            RkNxWXovZHVFUHM1by9pNkdNem5pTFEKLS0tIDVKNE9mTGFaZjBZcXNxNEVUWndE
            em1RTWkraUlVODkvcTFFakw3YVJLRE0KqanwENmvkYpJyqmDpq8hvRplRu4eiz5v
            5Jh2f/qBaAZigsA4SRgBgMD+rwzSeE/wj92gPpA6ELFe5PKZN+SKWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T22:00:58Z"
    mac: ENC[AES256_GCM,data:YyKx3w71XeOmgpL3Fhm6zkLR1w8lU991S4VqIw7YBshd7Lp7L5lt1hmg41ALCjM5WtUsYh0ZUGLCEhJAmyMtD11DT8PimvhZfRV/2kFKjN5/XExkiJ0pR02fabxghMg2SP1zc2XBnU8T9+y8NHY1U0oD4dsq0Kx8i2E6jU6f3fU=,iv:jN0RBTHWqtw8RkhXZXGkgO/8ASeFPYVCujX1hbLIzkk=,tag:oG9sgZPcAeXK0RR3t5oZOg==,type:str]
    version: 3.13.2
