apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: healthchecks
    namespace: snacky
stringData:
    ping-key: ENC[AES256_GCM,data:TpOv9L2yPgSJgoLefRutXO+TwkP4og==,iv:sMtCZ1h1+SUAvmGxMiwRIgWbWx5xnELR0T/bWwfe3kE=,tag:7fbc/86Uh9XO3lmbLZjzXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNzRMUGp4UHU1UGJUUDFh
            Q1h2dzRkTUFWMGJTWkZlZkxDZUZkUVZIZEVNCjJKVUNWeUppUlM1ZXFucGxnN3pz
            RkNxWXovZHVFUHM1by9pNkdNem5pTFEKLS0tIDVKNE9mTGFaZjBZcXNxNEVUWndE
            em1RTWkraUlVODkvcTFFakw3YVJLRE0KqanwENmvkYpJyqmDpq8hvRplRu4eiz5v
            5Jh2f/qBaAZigsA4SRgBgMD+rwzSeE/wj92gPpA6ELFe5PKZN+SKWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T13:51:04Z"
    mac: ENC[AES256_GCM,data:EQHB8A7179eYo2aMR8uAP6BDqC5amvILm0xBR15xyDat5r1+267xmm7D24asnRiYdWpLIsE6lcJ9+LPrJHRsfYyvjWCpnjHhNthIVY08WLFtIi7PcrW/0QDZ2viWsGlzCVamwNn/P0kS+YAH7BXYMa6kW10hmg3+ITfs5CiznLk=,iv:JGDp4pprwYivBK0632FtG3uO5b7PSHEE5B22n+jp+tE=,tag:4KxMWP+f9NZA/dleJOVLPQ==,type:str]
    version: 3.13.2
