apiVersion: v1
kind: Secret
metadata:
    name: snacky
    namespace: snacky
type: Opaque
stringData:
    TANDOOR_TOKEN: ENC[AES256_GCM,data:Xi8LsDqXsNvzF9QZjJCsgttNuK0SD/yZgJazDxtKocTbkRaqkLmqGQ==,iv:FVxD/id5VMSYRgg+czHYP+HVGiBy9VRCoofKJdBuew4=,tag:vdUi7GHyozMO9d5WES7n5A==,type:str]
    OPENGYM_TOKEN: ENC[AES256_GCM,data:g4RsOCqLn2HCKZIpQsa7/w7q8uh1Dy7JE3GqbauQVfePITeGsyXhxV5y7BL284QoEcgR56p41DkpQ8aavbKg4KSyyI/HJ4pnFJLskA==,iv:F0kdTOAgqiJpPFdd6C6FwX2pm2nMZBt7QkqRlw+c+Os=,tag:DZBJgUm87F/kdWXGSd/QnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSDNWRzY4SHBVL1IzRlRB
            YTU4SS9NdzRaYkxMbU9XaTh5bzUyNE9YaERvCjExYUJxUHJ3MU9HUmdiMXN5citl
            V0VBUlZHOVFhR2d3V3JWT0VXbU9wdm8KLS0tIENaWitWMURRa203WldZTmFOVkta
            WVZWcE9PQWtyWm0xRmpIeGRLdnhBVEEKZRYZCyEaiek+6v1akEfT1FgMHVlZ22QW
            tcG9PJm8QeIUnqd5Awi1a0zr9aVNoUmX04fRVv9MtoHTkp6RsHTIMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T12:51:40Z"
    mac: ENC[AES256_GCM,data:BjPlDUR+qwOXukcCaXzKifOG+cQ7UqGUzQY+PNXf+OSKM/fC/voVYGgeDSaAQCcZkEHgYmYb7Ir34kskTFHhQbxGhvWInJhdwZqw1FCBBaGZd+72eyIunzW5hbYhE3jA/yTxg1oqWKMrB9mzmtU5NGWUbd3PvtYs2lN/MYpKzQw=,iv:xTwgpvCczc1KKJ2KBOKyhUJnlJPFkbvy4ie7zcsYbmw=,tag:XlTAV3ZulUUaF1kvCe5wfA==,type:str]
    version: 3.13.3
