apiVersion: v1
kind: Secret
metadata:
    name: snacky
    namespace: snacky
type: Opaque
stringData:
    TANDOOR_TOKEN: ""
    OPENGYM_TOKEN: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSDNWRzY4SHBVL1IzRlRB
            YTU4SS9NdzRaYkxMbU9XaTh5bzUyNE9YaERvCjExYUJxUHJ3MU9HUmdiMXN5citl
            V0VBUlZHOVFhR2d3V3JWT0VXbU9wdm8KLS0tIENaWitWMURRa203WldZTmFOVkta
            WVZWcE9PQWtyWm0xRmpIeGRLdnhBVEEKZRYZCyEaiek+6v1akEfT1FgMHVlZ22QW
            tcG9PJm8QeIUnqd5Awi1a0zr9aVNoUmX04fRVv9MtoHTkp6RsHTIMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:31:30Z"
    mac: ENC[AES256_GCM,data:FmTWbRz2xx75pTSZnCO4Ebjh0XOwuY8e5bmUeBUiq+8/7+ryjCvMg45mjkdiswwrU4FKsrypnW+2e/6gcknlZDow8tSLoa6sJ1jCD3iKI2/7v8bKJVL+fvFU4fMPUidmWIb56BNkkEDWkVINYut/3EjWVFCPHy3//mXOiH7vvOQ=,iv:FrXYbX4oQ9cQSb59QiNkp/lUTHz9jL/7aRTCkwvxIcs=,tag:nzNR99pS1OBCZdxc0Y+zFg==,type:str]
    version: 3.13.3
