apiVersion: v1
kind: Secret
metadata:
    name: grimmory-credentials
    namespace: grimmory
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:AsYhiZvkEvmLVnHgNJgs7pghZdDaZNCVQmWGmInpWNoukJtNElrQBM8VaqpRciCxWCB/3HrzSkcxMCvQ,iv:rMjSX5Zn+kK82l3tjNZ0Bhaop1HWnbj/5SeLua6H5JI=,tag:6lW/27Gv1y5+Cp7X1Buw3w==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:laFCG59sE7mXjB4bQUJqinIRT8/4AvKi7+qdVOlknszYU7utzXS9aaBSuLeNKhgee293rJ42ft9UmbcH,iv:dinJOoqxdu2oiAQBTTfYZ0hiQ/SJQh2QH5Ul1vpIvCw=,tag:XpllxPPyZn7SjOwyT4XA5A==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTW41eGZ2V2Jyc3l4MUVa
            b3Z5TFFGV2U1S1NYYjVIRUw5bFFhbnRsUmxzCnlkSFNCWmhCSERLSkUxWUtPVU5v
            VWZ6bUplR3Avck0xL0lGTTZDWExvUmsKLS0tIHR1QlJQMXU1L0tuRGY1MjZ2SDZZ
            ZldTSzhKUW8rRzMyZFZtSVMzUjJZYWcKD89hrAn0yy+zcCrpqNUCkqGBh+JfhhBE
            GEAWtl1M9HrLygpGeDtoVHSq87X/Q5Pzgbcq2cH7XM06UfFhTAwRIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T17:51:39Z"
    mac: ENC[AES256_GCM,data:m0zBZsw47PjbrokFcur4mwqECM3dma4p7KIP6kaHMxmyjVnpQAuv9wkRNq7oHkOqdIygMjG8DYplybhhOIsMqAAqaUsrpHomgVnNsWYFTFwOzS2BXljS5MbcRK41jQUI55CTzbFA3QE2S2AOmfaG57+plVLLOYZC7bWdJ81dW9w=,iv:3vZQP25GWrTQz49qOeMlRb0E251yD0YmJ5/flx4E8Gg=,tag:ccaotAtkeQRmNd+jZX8h5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
